
import { QuantumCircuit } from '@/hooks/useCircuitBuilder';

class QOSMExporter {
  export(circuit: QuantumCircuit, format: string): string {
    switch (format.toLowerCase()) {
      case 'qasm':
        return this.exportQASM(circuit);
      case 'json':
        return this.exportJSON(circuit);
      case 'python':
        return this.exportPython(circuit);
      case 'javascript':
        return this.exportJavaScript(circuit);
      default:
        throw new Error(`Unsupported export format: ${format}`);
    }
  }

  private exportQASM(circuit: QuantumCircuit): string {
    let qasm = 'OPENQASM 2.0;\n';
    qasm += 'include "qelib1.inc";\n\n';
    qasm += `qreg q[${circuit.qubits.length}];\n`;
    qasm += `creg c[${circuit.qubits.length}];\n\n`;

    // Sort gates by layer
    const sortedGates = [...circuit.gates].sort((a, b) => a.layer - b.layer);

    for (const gate of sortedGates) {
      const qubitIndices = gate.qubits.map(qId => 
        circuit.qubits.findIndex(q => q.id === qId)
      );

      switch (gate.type) {
        case 'H':
          qasm += `h q[${qubitIndices[0]}];\n`;
          break;
        case 'X':
          qasm += `x q[${qubitIndices[0]}];\n`;
          break;
        case 'Y':
          qasm += `y q[${qubitIndices[0]}];\n`;
          break;
        case 'Z':
          qasm += `z q[${qubitIndices[0]}];\n`;
          break;
        case 'S':
          qasm += `s q[${qubitIndices[0]}];\n`;
          break;
        case 'T':
          qasm += `t q[${qubitIndices[0]}];\n`;
          break;
        case 'RX':
          qasm += `rx(${gate.params?.angle || 0}) q[${qubitIndices[0]}];\n`;
          break;
        case 'RY':
          qasm += `ry(${gate.params?.angle || 0}) q[${qubitIndices[0]}];\n`;
          break;
        case 'RZ':
          qasm += `rz(${gate.params?.angle || 0}) q[${qubitIndices[0]}];\n`;
          break;
        case 'CNOT':
          qasm += `cx q[${qubitIndices[0]}],q[${qubitIndices[1]}];\n`;
          break;
        case 'CZ':
          qasm += `cz q[${qubitIndices[0]}],q[${qubitIndices[1]}];\n`;
          break;
        case 'SWAP':
          qasm += `swap q[${qubitIndices[0]}],q[${qubitIndices[1]}];\n`;
          break;
        case 'TOFFOLI':
          qasm += `ccx q[${qubitIndices[0]}],q[${qubitIndices[1]}],q[${qubitIndices[2]}];\n`;
          break;
        case 'M':
          qasm += `measure q[${qubitIndices[0]}] -> c[${qubitIndices[0]}];\n`;
          break;
      }
    }

    return qasm;
  }

  private exportJSON(circuit: QuantumCircuit): string {
    const exportData = {
      name: circuit.name,
      description: circuit.description,
      qubits: circuit.qubits.length,
      gates: circuit.gates.map(gate => ({
        type: gate.type,
        qubits: gate.qubits.map(qId => circuit.qubits.findIndex(q => q.id === qId)),
        layer: gate.layer,
        params: gate.params
      })),
      metadata: circuit.metadata
    };

    return JSON.stringify(exportData, null, 2);
  }

  private exportPython(circuit: QuantumCircuit): string {
    let python = `# Quantum Circuit: ${circuit.name}\n`;
    python += `# Generated by QOSim\n\n`;
    python += `from qiskit import QuantumCircuit, execute, Aer\n`;
    python += `from qiskit.visualization import plot_histogram\n`;
    python += `import numpy as np\n\n`;
    
    python += `# Create quantum circuit\n`;
    python += `qc = QuantumCircuit(${circuit.qubits.length}, ${circuit.qubits.length})\n\n`;

    // Sort gates by layer
    const sortedGates = [...circuit.gates].sort((a, b) => a.layer - b.layer);

    for (const gate of sortedGates) {
      const qubitIndices = gate.qubits.map(qId => 
        circuit.qubits.findIndex(q => q.id === qId)
      );

      switch (gate.type) {
        case 'H':
          python += `qc.h(${qubitIndices[0]})\n`;
          break;
        case 'X':
          python += `qc.x(${qubitIndices[0]})\n`;
          break;
        case 'Y':
          python += `qc.y(${qubitIndices[0]})\n`;
          break;
        case 'Z':
          python += `qc.z(${qubitIndices[0]})\n`;
          break;
        case 'S':
          python += `qc.s(${qubitIndices[0]})\n`;
          break;
        case 'T':
          python += `qc.t(${qubitIndices[0]})\n`;
          break;
        case 'RX':
          python += `qc.rx(${gate.params?.angle || 0}, ${qubitIndices[0]})\n`;
          break;
        case 'RY':
          python += `qc.ry(${gate.params?.angle || 0}, ${qubitIndices[0]})\n`;
          break;
        case 'RZ':
          python += `qc.rz(${gate.params?.angle || 0}, ${qubitIndices[0]})\n`;
          break;
        case 'CNOT':
          python += `qc.cx(${qubitIndices[0]}, ${qubitIndices[1]})\n`;
          break;
        case 'CZ':
          python += `qc.cz(${qubitIndices[0]}, ${qubitIndices[1]})\n`;
          break;
        case 'SWAP':
          python += `qc.swap(${qubitIndices[0]}, ${qubitIndices[1]})\n`;
          break;
        case 'TOFFOLI':
          python += `qc.ccx(${qubitIndices[0]}, ${qubitIndices[1]}, ${qubitIndices[2]})\n`;
          break;
        case 'M':
          python += `qc.measure(${qubitIndices[0]}, ${qubitIndices[0]})\n`;
          break;
      }
    }

    python += `\n# Execute the circuit\n`;
    python += `backend = Aer.get_backend('qasm_simulator')\n`;
    python += `job = execute(qc, backend, shots=1024)\n`;
    python += `result = job.result()\n`;
    python += `counts = result.get_counts(qc)\n\n`;
    python += `# Display results\n`;
    python += `print("Measurement results:")\n`;
    python += `print(counts)\n`;
    python += `print(qc.draw())\n`;

    return python;
  }

  private exportJavaScript(circuit: QuantumCircuit): string {
    let js = `// Quantum Circuit: ${circuit.name}\n`;
    js += `// Generated by QOSim\n\n`;
    js += `import { QuantumCircuit, QuantumSimulator } from 'qosim-sdk';\n\n`;
    
    js += `// Create quantum circuit\n`;
    js += `const qc = new QuantumCircuit(${circuit.qubits.length});\n\n`;

    // Sort gates by layer
    const sortedGates = [...circuit.gates].sort((a, b) => a.layer - b.layer);

    for (const gate of sortedGates) {
      const qubitIndices = gate.qubits.map(qId => 
        circuit.qubits.findIndex(q => q.id === qId)
      );

      switch (gate.type) {
        case 'H':
          js += `qc.h(${qubitIndices[0]});\n`;
          break;
        case 'X':
          js += `qc.x(${qubitIndices[0]});\n`;
          break;
        case 'Y':
          js += `qc.y(${qubitIndices[0]});\n`;
          break;
        case 'Z':
          js += `qc.z(${qubitIndices[0]});\n`;
          break;
        case 'RX':
          js += `qc.rx(${gate.params?.angle || 0}, ${qubitIndices[0]});\n`;
          break;
        case 'RY':
          js += `qc.ry(${gate.params?.angle || 0}, ${qubitIndices[0]});\n`;
          break;
        case 'RZ':
          js += `qc.rz(${gate.params?.angle || 0}, ${qubitIndices[0]});\n`;
          break;
        case 'CNOT':
          js += `qc.cnot(${qubitIndices[0]}, ${qubitIndices[1]});\n`;
          break;
        case 'CZ':
          js += `qc.cz(${qubitIndices[0]}, ${qubitIndices[1]});\n`;
          break;
        case 'SWAP':
          js += `qc.swap(${qubitIndices[0]}, ${qubitIndices[1]});\n`;
          break;
        case 'M':
          js += `qc.measure(${qubitIndices[0]});\n`;
          break;
      }
    }

    js += `\n// Execute the circuit\n`;
    js += `const simulator = new QuantumSimulator();\n`;
    js += `const result = simulator.run(qc, { shots: 1024 });\n`;
    js += `console.log('Measurement results:', result.counts);\n`;
    js += `console.log('State vector:', result.stateVector);\n`;

    return js;
  }
}

export const qosmExporter = new QOSMExporter();
