
import { Gate } from '@/hooks/useCircuitWorkspace';
import { QOSimSDK, QuantumCircuit } from '@/sdk/qosim-sdk';

export interface CircuitExportFormat {
  python: string;
  javascript: string;
  qasm: string;
  json: string;
}

export interface CircuitMetadata {
  name: string;
  description?: string;
  author?: string;
  version: string;
  tags: string[];
  comments: Record<string, string>; // gateId -> comment
  created: Date;
  lastModified: Date;
}

export class CircuitIntegrationService {
  private sdk: QOSimSDK;

  constructor() {
    this.sdk = new QOSimSDK();
  }

  async exportCircuitToCode(gates: Gate[], metadata: CircuitMetadata): Promise<CircuitExportFormat> {
    const circuit = this.gatesToQuantumCircuit(gates, metadata);
    
    return {
      python: this.generatePythonCode(circuit, metadata),
      javascript: this.generateJavaScriptCode(circuit, metadata),
      qasm: this.sdk.exportCircuit(circuit, 'qasm'),
      json: this.sdk.exportCircuit(circuit, 'json')
    };
  }

  async importCircuitFromCode(code: string, format: 'python' | 'javascript' | 'qasm' | 'json'): Promise<{
    gates: Gate[];
    metadata: CircuitMetadata;
  }> {
    let circuit: QuantumCircuit;
    let metadata: CircuitMetadata;

    switch (format) {
      case 'python':
        ({ circuit, metadata } = this.parsePythonCode(code));
        break;
      case 'javascript':
        ({ circuit, metadata } = this.parseJavaScriptCode(code));
        break;
      case 'qasm':
        ({ circuit, metadata } = this.parseQASMCode(code));
        break;
      case 'json':
        ({ circuit, metadata } = this.parseJSONCode(code));
        break;
      default:
        throw new Error(`Unsupported format: ${format}`);
    }

    return {
      gates: this.quantumCircuitToGates(circuit),
      metadata
    };
  }

  private gatesToQuantumCircuit(gates: Gate[], metadata: CircuitMetadata): QuantumCircuit {
    const circuit = this.sdk.createCircuit(metadata.name, 5, metadata.description);
    
    gates.forEach(gate => {
      circuit.gates.push({
        type: gate.type.toLowerCase(),
        qubit: gate.qubit || 0,
        controlQubit: gate.controlQubit,
        angle: gate.angle,
        parameters: gate.params
      });
    });

    return circuit;
  }

  private quantumCircuitToGates(circuit: QuantumCircuit): Gate[] {
    return circuit.gates.map((gate, index) => ({
      id: `imported-gate-${index}`,
      type: gate.type.toUpperCase(),
      qubit: gate.qubit,
      position: index,
      controlQubit: gate.controlQubit,
      angle: gate.angle,
      params: gate.parameters
    }));
  }

  private generatePythonCode(circuit: QuantumCircuit, metadata: CircuitMetadata): string {
    let code = `# ${metadata.name}\n`;
    code += `# ${metadata.description || 'Quantum Circuit'}\n`;
    code += `# Generated by QOSim on ${new Date().toISOString()}\n\n`;
    code += `from qiskit import QuantumCircuit, execute, Aer\n`;
    code += `from qiskit.visualization import plot_histogram\n\n`;
    code += `# Create quantum circuit\n`;
    code += `qc = QuantumCircuit(${circuit.qubits})\n\n`;

    circuit.gates.forEach(gate => {
      const comment = metadata.comments[gate.type] || '';
      switch (gate.type.toLowerCase()) {
        case 'h':
          code += `qc.h(${gate.qubit})${comment ? `  # ${comment}` : ''}\n`;
          break;
        case 'x':
          code += `qc.x(${gate.qubit})${comment ? `  # ${comment}` : ''}\n`;
          break;
        case 'cnot':
          code += `qc.cx(${gate.controlQubit}, ${gate.qubit})${comment ? `  # ${comment}` : ''}\n`;
          break;
        default:
          code += `qc.${gate.type.toLowerCase()}(${gate.qubit})${comment ? `  # ${comment}` : ''}\n`;
      }
    });

    code += `\n# Execute circuit\n`;
    code += `backend = Aer.get_backend('qasm_simulator')\n`;
    code += `job = execute(qc, backend, shots=1024)\n`;
    code += `result = job.result()\n`;
    code += `counts = result.get_counts(qc)\n`;
    code += `print(counts)\n`;

    return code;
  }

  private generateJavaScriptCode(circuit: QuantumCircuit, metadata: CircuitMetadata): string {
    let code = `// ${metadata.name}\n`;
    code += `// ${metadata.description || 'Quantum Circuit'}\n`;
    code += `// Generated by QOSim on ${new Date().toISOString()}\n\n`;
    code += `import { QOSimSDK } from '@/sdk/qosim-sdk';\n\n`;
    code += `const sdk = new QOSimSDK();\n`;
    code += `await sdk.initialize();\n\n`;
    code += `// Create quantum circuit\n`;
    code += `let circuit = sdk.createCircuit('${metadata.name}', ${circuit.qubits});\n\n`;

    circuit.gates.forEach(gate => {
      const comment = metadata.comments[gate.type] || '';
      const gateConfig = {
        type: gate.type,
        qubit: gate.qubit,
        ...(gate.controlQubit && { controlQubit: gate.controlQubit }),
        ...(gate.angle && { angle: gate.angle })
      };
      
      code += `circuit = sdk.addGate(circuit, ${JSON.stringify(gateConfig)});${comment ? ` // ${comment}` : ''}\n`;
    });

    code += `\n// Simulate circuit\n`;
    code += `const result = await sdk.simulate(circuit);\n`;
    code += `console.log('Simulation result:', result);\n`;

    return code;
  }

  private parsePythonCode(code: string): { circuit: QuantumCircuit; metadata: CircuitMetadata } {
    // Basic parsing - can be enhanced
    const lines = code.split('\n');
    const circuit = this.sdk.createCircuit('Imported Circuit', 5);
    const metadata: CircuitMetadata = {
      name: 'Imported Circuit',
      version: '1.0.0',
      tags: [],
      comments: {},
      created: new Date(),
      lastModified: new Date()
    };

    lines.forEach(line => {
      const trimmed = line.trim();
      if (trimmed.startsWith('qc.h(')) {
        const qubit = parseInt(trimmed.match(/\d+/)?.[0] || '0');
        circuit.gates.push({ type: 'h', qubit });
      } else if (trimmed.startsWith('qc.x(')) {
        const qubit = parseInt(trimmed.match(/\d+/)?.[0] || '0');
        circuit.gates.push({ type: 'x', qubit });
      } else if (trimmed.startsWith('qc.cx(')) {
        const matches = trimmed.match(/\d+/g);
        if (matches && matches.length >= 2) {
          circuit.gates.push({ 
            type: 'cnot', 
            controlQubit: parseInt(matches[0]), 
            qubit: parseInt(matches[1]) 
          });
        }
      }
    });

    return { circuit, metadata };
  }

  private parseJavaScriptCode(code: string): { circuit: QuantumCircuit; metadata: CircuitMetadata } {
    // Basic parsing - can be enhanced
    const circuit = this.sdk.createCircuit('Imported Circuit', 5);
    const metadata: CircuitMetadata = {
      name: 'Imported Circuit',
      version: '1.0.0',
      tags: [],
      comments: {},
      created: new Date(),
      lastModified: new Date()
    };

    // Parse addGate calls
    const gateMatches = code.matchAll(/sdk\.addGate\(circuit,\s*({[^}]+})/g);
    for (const match of gateMatches) {
      try {
        const gateConfig = JSON.parse(match[1]);
        circuit.gates.push(gateConfig);
      } catch (e) {
        console.warn('Failed to parse gate config:', match[1]);
      }
    }

    return { circuit, metadata };
  }

  private parseQASMCode(code: string): { circuit: QuantumCircuit; metadata: CircuitMetadata } {
    const circuit = this.sdk.createCircuit('QASM Circuit', 5);
    const metadata: CircuitMetadata = {
      name: 'QASM Circuit',
      version: '1.0.0',
      tags: [],
      comments: {},
      created: new Date(),
      lastModified: new Date()
    };

    const lines = code.split('\n');
    lines.forEach(line => {
      const trimmed = line.trim();
      if (trimmed.startsWith('h q[')) {
        const qubit = parseInt(trimmed.match(/\d+/)?.[0] || '0');
        circuit.gates.push({ type: 'h', qubit });
      } else if (trimmed.startsWith('x q[')) {
        const qubit = parseInt(trimmed.match(/\d+/)?.[0] || '0');
        circuit.gates.push({ type: 'x', qubit });
      } else if (trimmed.startsWith('cx q[')) {
        const matches = trimmed.match(/\d+/g);
        if (matches && matches.length >= 2) {
          circuit.gates.push({ 
            type: 'cnot', 
            controlQubit: parseInt(matches[0]), 
            qubit: parseInt(matches[1]) 
          });
        }
      }
    });

    return { circuit, metadata };
  }

  private parseJSONCode(code: string): { circuit: QuantumCircuit; metadata: CircuitMetadata } {
    const data = JSON.parse(code);
    const circuit = data.circuit || this.sdk.createCircuit('JSON Circuit', 5);
    const metadata: CircuitMetadata = data.metadata || {
      name: 'JSON Circuit',
      version: '1.0.0',
      tags: [],
      comments: {},
      created: new Date(),
      lastModified: new Date()
    };

    return { circuit, metadata };
  }
}
