
import { useToast } from '@/hooks/use-toast';
import { trackEvent } from '@/lib/analytics';

interface Gate {
  id: string;
  type: string;
  qubit?: number;
  qubits?: number[];
  position: number;
  angle?: number;
  label?: string;
  comment?: string;
}

interface ExportOptions {
  projectName: string;
}

export function useExportHandlers(
  circuit: Gate[], 
  numQubits: number, 
  options: ExportOptions
) {
  const { toast } = useToast();

  const generateCircuitData = (gates: Gate[]) => {
    return gates
      .sort((a, b) => a.position - b.position)
      .map(gate => ({
        gate: gate.type,
        qubit: gate.qubit,
        qubits: gate.qubits,
        time: gate.position,
        angle: gate.angle
      }));
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    try {
      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.style.display = 'none';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      return true;
    } catch (error) {
      console.error('Download failed:', error);
      return false;
    }
  };

  const handleExportJSON = () => {
    try {
      const data = generateCircuitData(circuit);
      const jsonContent = JSON.stringify(data, null, 2);
      const success = downloadFile(jsonContent, `${options.projectName}.json`, 'application/json');
      
      if (success) {
        trackEvent('circuit_exported', { format: 'json', gateCount: circuit.length });
        toast({ title: "JSON exported successfully!" });
      } else {
        throw new Error('Download failed');
      }
    } catch (error) {
      console.error('JSON export error:', error);
      toast({ title: "Export failed", description: "Could not export JSON file", variant: "destructive" });
    }
  };

  const handleExportQASM = () => {
    try {
      let qasm = `OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q[${numQubits}];\ncreg c[${numQubits}];\n\n`;
      
      const sortedCircuit = [...circuit].sort((a, b) => a.position - b.position);
      
      sortedCircuit.forEach(gate => {
        switch (gate.type) {
          case 'H':
            qasm += `h q[${gate.qubit}];\n`;
            break;
          case 'X':
            qasm += `x q[${gate.qubit}];\n`;
            break;
          case 'Y':
            qasm += `y q[${gate.qubit}];\n`;
            break;
          case 'Z':
            qasm += `z q[${gate.qubit}];\n`;
            break;
          case 'S':
            qasm += `s q[${gate.qubit}];\n`;
            break;
          case 'T':
            qasm += `t q[${gate.qubit}];\n`;
            break;
          case 'CNOT':
            if (gate.qubits && gate.qubits.length >= 2) {
              qasm += `cx q[${gate.qubits[0]}],q[${gate.qubits[1]}];\n`;
            }
            break;
          case 'RX':
            qasm += `rx(${gate.angle || Math.PI/2}) q[${gate.qubit}];\n`;
            break;
          case 'RY':
            qasm += `ry(${gate.angle || Math.PI/2}) q[${gate.qubit}];\n`;
            break;
          case 'RZ':
            qasm += `rz(${gate.angle || Math.PI/2}) q[${gate.qubit}];\n`;
            break;
          case 'M':
            qasm += `measure q[${gate.qubit}] -> c[${gate.qubit}];\n`;
            break;
        }
      });
      
      const success = downloadFile(qasm, `${options.projectName}.qasm`, 'text/plain');
      
      if (success) {
        trackEvent('circuit_exported', { format: 'qasm', gateCount: circuit.length });
        toast({ title: "QASM exported successfully!" });
      } else {
        throw new Error('Download failed');
      }
    } catch (error) {
      console.error('QASM export error:', error);
      toast({ title: "Export failed", description: "Could not export QASM file", variant: "destructive" });
    }
  };

  const handleExportPython = () => {
    try {
      let python = `# Quantum Circuit - ${options.projectName}\n`;
      python += `# Generated by QOSim\n\n`;
      python += `from qiskit import QuantumCircuit, execute, Aer\n`;
      python += `from qiskit.visualization import plot_histogram\n`;
      python += `import numpy as np\n\n`;
      python += `# Create quantum circuit\n`;
      python += `qc = QuantumCircuit(${numQubits}, ${numQubits})\n\n`;
      
      const sortedCircuit = [...circuit].sort((a, b) => a.position - b.position);
      
      sortedCircuit.forEach(gate => {
        switch (gate.type) {
          case 'H':
            python += `qc.h(${gate.qubit})  # Hadamard gate\n`;
            break;
          case 'X':
            python += `qc.x(${gate.qubit})  # Pauli-X gate\n`;
            break;
          case 'Y':
            python += `qc.y(${gate.qubit})  # Pauli-Y gate\n`;
            break;
          case 'Z':
            python += `qc.z(${gate.qubit})  # Pauli-Z gate\n`;
            break;
          case 'S':
            python += `qc.s(${gate.qubit})  # S gate\n`;
            break;
          case 'T':
            python += `qc.t(${gate.qubit})  # T gate\n`;
            break;
          case 'CNOT':
            if (gate.qubits && gate.qubits.length >= 2) {
              python += `qc.cx(${gate.qubits[0]}, ${gate.qubits[1]})  # CNOT gate\n`;
            }
            break;
          case 'RX':
            python += `qc.rx(${gate.angle || 'np.pi/2'}, ${gate.qubit})  # RX rotation\n`;
            break;
          case 'RY':
            python += `qc.ry(${gate.angle || 'np.pi/2'}, ${gate.qubit})  # RY rotation\n`;
            break;
          case 'RZ':
            python += `qc.rz(${gate.angle || 'np.pi/2'}, ${gate.qubit})  # RZ rotation\n`;
            break;
          case 'M':
            python += `qc.measure(${gate.qubit}, ${gate.qubit})  # Measurement\n`;
            break;
        }
      });
      
      python += `\n# Execute the circuit\n`;
      python += `backend = Aer.get_backend('qasm_simulator')\n`;
      python += `job = execute(qc, backend, shots=1024)\n`;
      python += `result = job.result()\n`;
      python += `counts = result.get_counts(qc)\n\n`;
      python += `# Display results\n`;
      python += `print("Measurement results:")\n`;
      python += `print(counts)\n\n`;
      python += `# Uncomment to visualize\n`;
      python += `# plot_histogram(counts)\n`;
      python += `# print(qc.draw())\n`;
      
      const success = downloadFile(python, `${options.projectName}.py`, 'text/plain');
      
      if (success) {
        trackEvent('circuit_exported', { format: 'python', gateCount: circuit.length });
        toast({ title: "Python exported successfully!" });
      } else {
        throw new Error('Download failed');
      }
    } catch (error) {
      console.error('Python export error:', error);
      toast({ title: "Export failed", description: "Could not export Python file", variant: "destructive" });
    }
  };

  return {
    handleExportJSON,
    handleExportQASM,
    handleExportPython
  };
}
