
import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Download, Copy, Check, Code, FileText } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import type { QuantumGate } from '@/hooks/useCircuitBuilder';

interface ExportPanelProps {
  circuit: QuantumGate[];
  onExport: (format: 'qasm' | 'python' | 'javascript' | 'json') => void;
}

export function ExportPanel({ circuit, onExport }: ExportPanelProps) {
  const [selectedFormat, setSelectedFormat] = useState<'qasm' | 'python' | 'javascript' | 'json'>('qasm');
  const [projectName, setProjectName] = useState('quantum_circuit');
  const [exportedCode, setExportedCode] = useState('');
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const generateQASM = () => {
    const numQubits = Math.max(...circuit.flatMap(g => g.qubits)) + 1;
    
    let qasm = `OPENQASM 2.0;\n`;
    qasm += `include "qelib1.inc";\n`;
    qasm += `qreg q[${numQubits}];\n`;
    qasm += `creg c[${numQubits}];\n\n`;
    
    // Sort gates by layer
    const sortedGates = [...circuit].sort((a, b) => a.layer - b.layer);
    
    sortedGates.forEach(gate => {
      switch (gate.type) {
        case 'H':
          qasm += `h q[${gate.qubits[0]}];\n`;
          break;
        case 'X':
          qasm += `x q[${gate.qubits[0]}];\n`;
          break;
        case 'Y':
          qasm += `y q[${gate.qubits[0]}];\n`;
          break;
        case 'Z':
          qasm += `z q[${gate.qubits[0]}];\n`;
          break;
        case 'S':
          qasm += `s q[${gate.qubits[0]}];\n`;
          break;
        case 'T':
          qasm += `t q[${gate.qubits[0]}];\n`;
          break;
        case 'CNOT':
          qasm += `cx q[${gate.qubits[0]}],q[${gate.qubits[1]}];\n`;
          break;
        case 'CZ':
          qasm += `cz q[${gate.qubits[0]}],q[${gate.qubits[1]}];\n`;
          break;
        case 'RX':
          qasm += `rx(${gate.angle || 'pi/2'}) q[${gate.qubits[0]}];\n`;
          break;
        case 'RY':
          qasm += `ry(${gate.angle || 'pi/2'}) q[${gate.qubits[0]}];\n`;
          break;
        case 'RZ':
          qasm += `rz(${gate.angle || 'pi/2'}) q[${gate.qubits[0]}];\n`;
          break;
        case 'MEASURE':
          qasm += `measure q[${gate.qubits[0]}] -> c[${gate.qubits[0]}];\n`;
          break;
        default:
          qasm += `// Unsupported gate: ${gate.type}\n`;
      }
    });
    
    return qasm;
  };

  const generatePython = () => {
    const numQubits = Math.max(...circuit.flatMap(g => g.qubits)) + 1;
    
    let python = `# Quantum Circuit - ${projectName}\n`;
    python += `# Generated by Quantum Circuit Builder\n\n`;
    python += `from qiskit import QuantumCircuit, execute, Aer\n`;
    python += `from qiskit.visualization import plot_histogram\n`;
    python += `import numpy as np\n\n`;
    python += `# Create quantum circuit\n`;
    python += `qc = QuantumCircuit(${numQubits}, ${numQubits})\n\n`;
    
    // Sort gates by layer
    const sortedGates = [...circuit].sort((a, b) => a.layer - b.layer);
    
    sortedGates.forEach(gate => {
      switch (gate.type) {
        case 'H':
          python += `qc.h(${gate.qubits[0]})\n`;
          break;
        case 'X':
          python += `qc.x(${gate.qubits[0]})\n`;
          break;
        case 'Y':
          python += `qc.y(${gate.qubits[0]})\n`;
          break;
        case 'Z':
          python += `qc.z(${gate.qubits[0]})\n`;
          break;
        case 'S':
          python += `qc.s(${gate.qubits[0]})\n`;
          break;
        case 'T':
          python += `qc.t(${gate.qubits[0]})\n`;
          break;
        case 'CNOT':
          python += `qc.cx(${gate.qubits[0]}, ${gate.qubits[1]})\n`;
          break;
        case 'CZ':
          python += `qc.cz(${gate.qubits[0]}, ${gate.qubits[1]})\n`;
          break;
        case 'RX':
          python += `qc.rx(${gate.angle || 'np.pi/2'}, ${gate.qubits[0]})\n`;
          break;
        case 'RY':
          python += `qc.ry(${gate.angle || 'np.pi/2'}, ${gate.qubits[0]})\n`;
          break;
        case 'RZ':
          python += `qc.rz(${gate.angle || 'np.pi/2'}, ${gate.qubits[0]})\n`;
          break;
        case 'MEASURE':
          python += `qc.measure(${gate.qubits[0]}, ${gate.qubits[0]})\n`;
          break;
        default:
          python += `# Unsupported gate: ${gate.type}\n`;
      }
    });
    
    python += `\n# Execute the circuit\n`;
    python += `backend = Aer.get_backend('qasm_simulator')\n`;
    python += `job = execute(qc, backend, shots=1024)\n`;
    python += `result = job.result()\n`;
    python += `counts = result.get_counts(qc)\n\n`;
    python += `# Display results\n`;
    python += `print("Measurement results:")\n`;
    python += `print(counts)\n\n`;
    python += `# Visualize circuit\n`;
    python += `print(qc.draw())\n`;
    
    return python;
  };

  const generateJavaScript = () => {
    let js = `// Quantum Circuit - ${projectName}\n`;
    js += `// Generated by Quantum Circuit Builder\n\n`;
    js += `import { QuantumCircuit, QuantumSimulator } from 'qosim-sdk';\n\n`;
    js += `// Create quantum circuit\n`;
    js += `const circuit = new QuantumCircuit();\n\n`;
    
    // Sort gates by layer
    const sortedGates = [...circuit].sort((a, b) => a.layer - b.layer);
    
    sortedGates.forEach(gate => {
      switch (gate.type) {
        case 'H':
          js += `circuit.h(${gate.qubits[0]});\n`;
          break;
        case 'X':
          js += `circuit.x(${gate.qubits[0]});\n`;
          break;
        case 'Y':
          js += `circuit.y(${gate.qubits[0]});\n`;
          break;
        case 'Z':
          js += `circuit.z(${gate.qubits[0]});\n`;
          break;
        case 'S':
          js += `circuit.s(${gate.qubits[0]});\n`;
          break;
        case 'T':
          js += `circuit.t(${gate.qubits[0]});\n`;
          break;
        case 'CNOT':
          js += `circuit.cnot(${gate.qubits[0]}, ${gate.qubits[1]});\n`;
          break;
        case 'CZ':
          js += `circuit.cz(${gate.qubits[0]}, ${gate.qubits[1]});\n`;
          break;
        case 'RX':
          js += `circuit.rx(${gate.angle || 'Math.PI/2'}, ${gate.qubits[0]});\n`;
          break;
        case 'RY':
          js += `circuit.ry(${gate.angle || 'Math.PI/2'}, ${gate.qubits[0]});\n`;
          break;
        case 'RZ':
          js += `circuit.rz(${gate.angle || 'Math.PI/2'}, ${gate.qubits[0]});\n`;
          break;
        case 'MEASURE':
          js += `circuit.measure(${gate.qubits[0]});\n`;
          break;
        default:
          js += `// Unsupported gate: ${gate.type}\n`;
      }
    });
    
    js += `\n// Simulate the circuit\n`;
    js += `const simulator = new QuantumSimulator();\n`;
    js += `const result = simulator.simulate(circuit);\n\n`;
    js += `// Display results\n`;
    js += `console.log('Simulation results:', result);\n`;
    js += `console.log('State vector:', result.stateVector);\n`;
    js += `console.log('Measurement probabilities:', result.measurementProbabilities);\n`;
    
    return js;
  };

  const generateJSON = () => {
    const circuitData = {
      metadata: {
        name: projectName,
        version: '1.0.0',
        created: new Date().toISOString(),
        description: 'Quantum circuit exported from Quantum Circuit Builder'
      },
      qubits: Math.max(...circuit.flatMap(g => g.qubits)) + 1,
      gates: circuit.map(gate => ({
        id: gate.id,
        type: gate.type,
        qubits: gate.qubits,
        layer: gate.layer,
        position: gate.position,
        ...(gate.angle && { angle: gate.angle }),
        ...(gate.params && { params: gate.params }),
        ...(gate.label && { label: gate.label }),
        ...(gate.comment && { comment: gate.comment })
      }))
    };
    
    return JSON.stringify(circuitData, null, 2);
  };

  const generateCode = () => {
    switch (selectedFormat) {
      case 'qasm':
        return generateQASM();
      case 'python':
        return generatePython();
      case 'javascript':
        return generateJavaScript();
      case 'json':
        return generateJSON();
      default:
        return '';
    }
  };

  const handleGenerate = () => {
    const code = generateCode();
    setExportedCode(code);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(exportedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    
    toast({
      title: "Code Copied",
      description: "Code has been copied to clipboard"
    });
  };

  const handleDownload = () => {
    const extensions = {
      qasm: 'qasm',
      python: 'py',
      javascript: 'js',
      json: 'json'
    };
    
    const blob = new Blob([exportedCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName}.${extensions[selectedFormat]}`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast({
      title: "File Downloaded",
      description: `Circuit exported as ${selectedFormat.toUpperCase()}`
    });
  };

  const formats = [
    { value: 'qasm', label: 'OpenQASM', description: 'Standard quantum assembly language' },
    { value: 'python', label: 'Python (Qiskit)', description: 'Python code using Qiskit framework' },
    { value: 'javascript', label: 'JavaScript (QOSim)', description: 'JavaScript code using QOSim SDK' },
    { value: 'json', label: 'JSON', description: 'Circuit data in JSON format' }
  ];

  return (
    <Card className="h-full">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Download className="w-5 h-5" />
          Export Circuit
        </CardTitle>
      </CardHeader>
      
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="project-name">Project Name</Label>
          <Input
            id="project-name"
            value={projectName}
            onChange={(e) => setProjectName(e.target.value)}
            placeholder="Enter project name"
          />
        </div>
        
        <div className="space-y-2">
          <Label htmlFor="format">Export Format</Label>
          <Select value={selectedFormat} onValueChange={(value: any) => setSelectedFormat(value)}>
            <SelectTrigger>
              <SelectValue placeholder="Select format" />
            </SelectTrigger>
            <SelectContent>
              {formats.map(format => (
                <SelectItem key={format.value} value={format.value}>
                  <div>
                    <div className="font-medium">{format.label}</div>
                    <div className="text-sm text-muted-foreground">{format.description}</div>
                  </div>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        
        <div className="flex gap-2">
          <Button onClick={handleGenerate} className="flex-1">
            <Code className="w-4 h-4 mr-2" />
            Generate Code
          </Button>
          <Button
            variant="outline"
            onClick={() => onExport(selectedFormat)}
            disabled={circuit.length === 0}
          >
            <FileText className="w-4 h-4 mr-2" />
            Export
          </Button>
        </div>
        
        {exportedCode && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label>Generated Code</Label>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleCopy}
                >
                  {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                  {copied ? 'Copied' : 'Copy'}
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleDownload}
                >
                  <Download className="w-4 h-4" />
                  Download
                </Button>
              </div>
            </div>
            
            <Textarea
              value={exportedCode}
              readOnly
              className="h-64 font-mono text-sm"
              placeholder="Generated code will appear here"
            />
          </div>
        )}
        
        {circuit.length === 0 && (
          <div className="text-center py-8 text-muted-foreground">
            <FileText className="w-12 h-12 mx-auto mb-4 opacity-50" />
            <p>Add gates to your circuit to export</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
