// Enhanced OpenQASM 2.0 Exporter with full QOSim compatibility
import { QuantumGateOp } from '@/lib/enhancedQuantumSimulator';

export interface QASMExportOptions {
  includeComments: boolean;
  includeHeaders: boolean;
  includeInitializations: boolean;
  includeMeasurements: boolean;
  qregName: string;
  cregName: string;
}

export interface QASMCircuit {
  name: string;
  qubits: number;
  gates: QuantumGateOp[];
  measurements?: Array<{ qubit: number; classical: number }>;
}

export class EnhancedOpenQASMExporter {
  private options: QASMExportOptions;

  constructor(options: Partial<QASMExportOptions> = {}) {
    this.options = {
      includeComments: true,
      includeHeaders: true,
      includeInitializations: true,
      includeMeasurements: true,
      qregName: 'q',
      cregName: 'c',
      ...options
    };
  }

  exportCircuit(circuit: QASMCircuit): string {
    console.log('🔄 Exporting circuit to OpenQASM 2.0...');
    
    const lines: string[] = [];

    // QASM Version and includes
    if (this.options.includeHeaders) {
      lines.push('OPENQASM 2.0;');
      lines.push('include "qelib1.inc";');
      lines.push('');
    }

    // Circuit metadata comment
    if (this.options.includeComments) {
      lines.push(`// Circuit: ${circuit.name}`);
      lines.push(`// Generated by QOSim at ${new Date().toISOString()}`);
      lines.push(`// Qubits: ${circuit.qubits}, Gates: ${circuit.gates.length}`);
      lines.push('');
    }

    // Register declarations
    lines.push(`qreg ${this.options.qregName}[${circuit.qubits}];`);
    lines.push(`creg ${this.options.cregName}[${circuit.qubits}];`);
    lines.push('');

    // Initialize qubits to |0⟩ if requested
    if (this.options.includeInitializations && this.options.includeComments) {
      lines.push('// Initialize all qubits to |0⟩ state');
      for (let i = 0; i < circuit.qubits; i++) {
        lines.push(`// ${this.options.qregName}[${i}] = |0⟩`);
      }
      lines.push('');
    }

    // Sort gates by position
    const sortedGates = [...circuit.gates].sort((a, b) => a.position - b.position);

    // Group gates by position for parallel execution
    const gateGroups = this.groupGatesByPosition(sortedGates);

    // Export gate groups
    gateGroups.forEach((gates, position) => {
      if (this.options.includeComments && gates.length > 1) {
        lines.push(`// Parallel gates at position ${position}`);
      }

      gates.forEach(gate => {
        const qasmInstruction = this.convertGateToQASM(gate);
        if (qasmInstruction) {
          if (this.options.includeComments) {
            lines.push(`${qasmInstruction} // ${gate.id}`);
          } else {
            lines.push(qasmInstruction);
          }
        }
      });

      if (gates.length > 1) {
        lines.push(''); // Add space after parallel gate groups
      }
    });

    // Add measurements
    if (this.options.includeMeasurements) {
      lines.push('');
      if (this.options.includeComments) {
        lines.push('// Measurements');
      }

      if (circuit.measurements && circuit.measurements.length > 0) {
        // Custom measurements
        circuit.measurements.forEach(measurement => {
          lines.push(`measure ${this.options.qregName}[${measurement.qubit}] -> ${this.options.cregName}[${measurement.classical}];`);
        });
      } else {
        // Default: measure all qubits
        lines.push(`measure ${this.options.qregName} -> ${this.options.cregName};`);
      }
    }

    const result = lines.join('\n') + '\n';
    console.log('✅ OpenQASM export completed');
    return result;
  }

  private groupGatesByPosition(gates: QuantumGateOp[]): Map<number, QuantumGateOp[]> {
    const groups = new Map<number, QuantumGateOp[]>();
    
    gates.forEach(gate => {
      const position = gate.position;
      if (!groups.has(position)) {
        groups.set(position, []);
      }
      groups.get(position)!.push(gate);
    });

    return groups;
  }

  private convertGateToQASM(gate: QuantumGateOp): string | null {
    const q = (qubit: number) => `${this.options.qregName}[${qubit}]`;
    
    switch (gate.type.toUpperCase()) {
      case 'I':
        return `id ${q(gate.qubits[0])};`;
      
      case 'X':
        return `x ${q(gate.qubits[0])};`;
      
      case 'Y':
        return `y ${q(gate.qubits[0])};`;
      
      case 'Z':
        return `z ${q(gate.qubits[0])};`;
      
      case 'H':
        return `h ${q(gate.qubits[0])};`;
      
      case 'S':
        return `s ${q(gate.qubits[0])};`;
      
      case 'SDG':
        return `sdg ${q(gate.qubits[0])};`;
      
      case 'T':
        return `t ${q(gate.qubits[0])};`;
      
      case 'TDG':
        return `tdg ${q(gate.qubits[0])};`;
      
      case 'RX':
        if (gate.angle !== undefined) {
          return `rx(${gate.angle}) ${q(gate.qubits[0])};`;
        }
        break;
      
      case 'RY':
        if (gate.angle !== undefined) {
          return `ry(${gate.angle}) ${q(gate.qubits[0])};`;
        }
        break;
      
      case 'RZ':
        if (gate.angle !== undefined) {
          return `rz(${gate.angle}) ${q(gate.qubits[0])};`;
        }
        break;
      
      case 'U1':
        if (gate.params && gate.params.length >= 1) {
          return `u1(${gate.params[0]}) ${q(gate.qubits[0])};`;
        }
        break;
      
      case 'U2':
        if (gate.params && gate.params.length >= 2) {
          return `u2(${gate.params[0]},${gate.params[1]}) ${q(gate.qubits[0])};`;
        }
        break;
      
      case 'U3':
        if (gate.params && gate.params.length >= 3) {
          return `u3(${gate.params[0]},${gate.params[1]},${gate.params[2]}) ${q(gate.qubits[0])};`;
        }
        break;
      
      case 'CNOT':
      case 'CX':
        if (gate.qubits.length >= 2) {
          const control = gate.control ?? gate.qubits[0];
          const target = gate.target ?? gate.qubits[1];
          return `cx ${q(control)},${q(target)};`;
        }
        break;
      
      case 'CY':
        if (gate.qubits.length >= 2) {
          const control = gate.control ?? gate.qubits[0];
          const target = gate.target ?? gate.qubits[1];
          return `cy ${q(control)},${q(target)};`;
        }
        break;
      
      case 'CZ':
        if (gate.qubits.length >= 2) {
          const control = gate.control ?? gate.qubits[0];
          const target = gate.target ?? gate.qubits[1];
          return `cz ${q(control)},${q(target)};`;
        }
        break;
      
      case 'SWAP':
        if (gate.qubits.length >= 2) {
          return `swap ${q(gate.qubits[0])},${q(gate.qubits[1])};`;
        }
        break;
      
      case 'TOFFOLI':
      case 'CCX':
        if (gate.qubits.length >= 3) {
          return `ccx ${q(gate.qubits[0])},${q(gate.qubits[1])},${q(gate.qubits[2])};`;
        }
        break;
      
      case 'CSWAP':
      case 'FREDKIN':
        if (gate.qubits.length >= 3) {
          return `cswap ${q(gate.qubits[0])},${q(gate.qubits[1])},${q(gate.qubits[2])};`;
        }
        break;
      
      case 'RESET':
        return `reset ${q(gate.qubits[0])};`;
      
      case 'MEASURE':
        const classical = gate.params?.[0] ?? gate.qubits[0];
        return `measure ${q(gate.qubits[0])} -> ${this.options.cregName}[${classical}];`;
      
      default:
        console.warn(`Unknown gate type for QASM export: ${gate.type}`);
        return `// Unknown gate: ${gate.type}`;
    }

    console.warn(`Invalid gate parameters for ${gate.type}:`, gate);
    return `// Invalid gate: ${gate.type}`;
  }

  // Validate QASM syntax
  validateQASM(qasm: string): { isValid: boolean; errors: string[] } {
    const errors: string[] = [];
    const lines = qasm.split('\n').filter(line => line.trim() && !line.trim().startsWith('//'));

    // Check for required header
    if (!lines.some(line => line.includes('OPENQASM'))) {
      errors.push('Missing OPENQASM version declaration');
    }

    // Check for register declarations
    const hasQreg = lines.some(line => line.match(/^qreg\s+\w+\[\d+\];/));
    const hasCreg = lines.some(line => line.match(/^creg\s+\w+\[\d+\];/));

    if (!hasQreg) {
      errors.push('Missing quantum register (qreg) declaration');
    }
    if (!hasCreg) {
      errors.push('Missing classical register (creg) declaration');
    }

    // Check for valid gate syntax
    lines.forEach((line, index) => {
      const trimmed = line.trim();
      if (trimmed && !trimmed.includes('OPENQASM') && !trimmed.includes('include') && 
          !trimmed.match(/^(qreg|creg)/) && !trimmed.endsWith(';')) {
        errors.push(`Line ${index + 1}: Statement should end with semicolon`);
      }
    });

    return {
      isValid: errors.length === 0,
      errors
    };
  }

  // Convert QOSim circuit to QASM format
  static fromQOSimCircuit(circuit: any): QASMCircuit {
    const gates: QuantumGateOp[] = circuit.gates.map((gate: any, index: number) => ({
      id: gate.id || `gate_${index}`,
      type: gate.type,
      qubits: gate.qubits || [gate.qubit].filter(q => q !== undefined),
      control: gate.control,
      target: gate.target,
      angle: gate.angle,
      params: gate.params,
      position: gate.position || index
    }));

    return {
      name: circuit.name || 'QOSim_Circuit',
      qubits: circuit.qubits?.length || Math.max(...gates.flatMap(g => g.qubits)) + 1,
      gates
    };
  }
}

// Export convenience function
export function exportToOpenQASM(circuit: any, options?: Partial<QASMExportOptions>): string {
  const exporter = new EnhancedOpenQASMExporter(options);
  const qasmCircuit = EnhancedOpenQASMExporter.fromQOSimCircuit(circuit);
  return exporter.exportCircuit(qasmCircuit);
}