// Enhanced JavaScript Exporter for QOSim circuits
import { QuantumGateOp } from '@/lib/enhancedQuantumSimulator';

export interface JSExportOptions {
  framework: 'vanilla' | 'qosim-sdk' | 'node';
  includeComments: boolean;
  includeImports: boolean;
  useES6: boolean;
  addVisualization: boolean;
  asyncExecution: boolean;
}

export interface JSCircuit {
  name: string;
  qubits: number;
  gates: QuantumGateOp[];
  shots?: number;
}

export class EnhancedJavaScriptExporter {
  private options: JSExportOptions;

  constructor(options: Partial<JSExportOptions> = {}) {
    this.options = {
      framework: 'qosim-sdk',
      includeComments: true,
      includeImports: true,
      useES6: true,
      addVisualization: false,
      asyncExecution: true,
      ...options
    };
  }

  exportCircuit(circuit: JSCircuit): string {
    console.log('🔄 Exporting circuit to JavaScript...');
    
    const lines: string[] = [];

    // Add header comment
    if (this.options.includeComments) {
      lines.push(`/**`);
      lines.push(` * Quantum Circuit: ${circuit.name}`);
      lines.push(` * Generated by QOSim at ${new Date().toISOString()}`);
      lines.push(` * Qubits: ${circuit.qubits}, Gates: ${circuit.gates.length}`);
      lines.push(` * Framework: ${this.options.framework}`);
      lines.push(` */`);
      lines.push('');
    }

    // Add imports
    if (this.options.includeImports) {
      lines.push(...this.generateImports());
      lines.push('');
    }

    // Generate main function
    switch (this.options.framework) {
      case 'qosim-sdk':
        lines.push(...this.generateQOSimSDKCode(circuit));
        break;
      case 'vanilla':
        lines.push(...this.generateVanillaJSCode(circuit));
        break;
      case 'node':
        lines.push(...this.generateNodeJSCode(circuit));
        break;
    }

    // Add execution code
    if (this.options.asyncExecution) {
      lines.push('');
      lines.push('// Execute the circuit');
      lines.push('runQuantumCircuit()');
      lines.push('  .then(result => {');
      lines.push('    console.log("Simulation completed:", result);');
      if (this.options.addVisualization) {
        lines.push('    visualizeResults(result);');
      }
      lines.push('  })');
      lines.push('  .catch(error => {');
      lines.push('    console.error("Simulation failed:", error);');
      lines.push('  });');
    }

    const result = lines.join('\n') + '\n';
    console.log('✅ JavaScript export completed');
    return result;
  }

  private generateImports(): string[] {
    const imports: string[] = [];

    switch (this.options.framework) {
      case 'qosim-sdk':
        if (this.options.useES6) {
          imports.push('import { QOSimSimulator } from "./qosim-sdk.js";');
        } else {
          imports.push('const { QOSimSimulator } = require("./qosim-sdk");');
        }
        break;
      
      case 'vanilla':
        imports.push('// Include qosim-core.js in your HTML:');
        imports.push('// <script src="qosim-core.js"></script>');
        break;
      
      case 'node':
        imports.push('const { QOSimSimulator } = require("qosim-node");');
        break;
    }

    return imports;
  }

  private generateQOSimSDKCode(circuit: JSCircuit): string[] {
    const lines: string[] = [];
    const funcName = this.options.asyncExecution ? 'async function runQuantumCircuit()' : 'function runQuantumCircuit()';
    
    lines.push(`${funcName} {`);
    
    if (this.options.includeComments) {
      lines.push(`  // Initialize ${circuit.qubits}-qubit quantum simulator`);
    }
    lines.push(`  const qc = new QOSimSimulator(${circuit.qubits});`);
    lines.push('');
    
    if (this.options.includeComments) {
      lines.push('  // Build the quantum circuit');
    }

    // Sort gates by position
    const sortedGates = [...circuit.gates].sort((a, b) => a.position - b.position);
    
    // Group gates by position for comments
    const gateGroups = this.groupGatesByPosition(sortedGates);
    
    gateGroups.forEach((gates, position) => {
      if (this.options.includeComments && gates.length > 1) {
        lines.push(`  // Position ${position} - Parallel gates`);
      }
      
      gates.forEach(gate => {
        const gateCode = this.convertGateToJS(gate);
        if (gateCode) {
          if (this.options.includeComments && gates.length === 1) {
            lines.push(`  ${gateCode} // ${gate.type} gate`);
          } else {
            lines.push(`  ${gateCode}`);
          }
        }
      });
    });

    lines.push('');
    if (this.options.includeComments) {
      lines.push('  // Run the simulation');
    }
    
    if (this.options.asyncExecution) {
      lines.push('  const result = await qc.run();');
    } else {
      lines.push('  qc.run();');
      lines.push('  const result = qc.getResult();');
    }
    
    lines.push('');
    if (this.options.includeComments) {
      lines.push('  // Get measurement results');
    }
    lines.push('  const probabilities = qc.getProbabilities();');
    lines.push('  const stateVector = qc.getStateVector();');
    lines.push('  const measurementCounts = qc.getMeasurementCounts();');
    lines.push('');
    lines.push('  return {');
    lines.push('    probabilities,');
    lines.push('    stateVector,');
    lines.push('    measurementCounts,');
    lines.push(`    shots: ${circuit.shots || 1024}`);
    lines.push('  };');
    lines.push('}');

    return lines;
  }

  private generateVanillaJSCode(circuit: JSCircuit): string[] {
    const lines: string[] = [];
    
    lines.push('function runQuantumCircuit() {');
    lines.push(`  // Initialize ${circuit.qubits}-qubit quantum circuit`);
    lines.push(`  const qc = new QOSimSimulator(${circuit.qubits});`);
    lines.push('');
    
    // Add gates
    const sortedGates = [...circuit.gates].sort((a, b) => a.position - b.position);
    sortedGates.forEach(gate => {
      const gateCode = this.convertGateToJS(gate);
      if (gateCode) {
        lines.push(`  ${gateCode}`);
      }
    });

    lines.push('');
    lines.push('  // Execute circuit');
    lines.push('  qc.run();');
    lines.push('');
    lines.push('  // Display results');
    lines.push('  const probabilities = qc.getProbabilities();');
    lines.push('  const basisStates = qc.getBasisStates();');
    lines.push('  ');
    lines.push('  console.log("Quantum Circuit Results:");');
    lines.push('  console.log("Probabilities:", probabilities);');
    lines.push('  console.log("Basis States:", basisStates);');
    lines.push('  ');
    lines.push('  return { probabilities, basisStates };');
    lines.push('}');

    return lines;
  }

  private generateNodeJSCode(circuit: JSCircuit): string[] {
    const lines: string[] = [];
    
    lines.push('async function runQuantumCircuit() {');
    lines.push('  try {');
    lines.push(`    // Initialize quantum simulator with ${circuit.qubits} qubits`);
    lines.push(`    const qc = new QOSimSimulator(${circuit.qubits});`);
    lines.push('');
    
    // Add gates
    const sortedGates = [...circuit.gates].sort((a, b) => a.position - b.position);
    sortedGates.forEach(gate => {
      const gateCode = this.convertGateToJS(gate);
      if (gateCode) {
        lines.push(`    ${gateCode}`);
      }
    });

    lines.push('');
    lines.push('    // Execute simulation');
    lines.push('    const result = await qc.simulate();');
    lines.push('');
    lines.push('    // Process results');
    lines.push('    console.log(`Circuit executed successfully:`);');
    lines.push('    console.log(`- Execution time: ${result.executionTime}ms`);');
    lines.push('    console.log(`- Fidelity: ${result.fidelity}`);');
    lines.push('    console.log(`- State vector magnitude: ${result.stateVector.length}`);');
    lines.push('');
    lines.push('    return result;');
    lines.push('  } catch (error) {');
    lines.push('    console.error("Quantum simulation failed:", error);');
    lines.push('    throw error;');
    lines.push('  }');
    lines.push('}');

    return lines;
  }

  private groupGatesByPosition(gates: QuantumGateOp[]): Map<number, QuantumGateOp[]> {
    const groups = new Map<number, QuantumGateOp[]>();
    
    gates.forEach(gate => {
      const position = gate.position;
      if (!groups.has(position)) {
        groups.set(position, []);
      }
      groups.get(position)!.push(gate);
    });

    return groups;
  }

  private convertGateToJS(gate: QuantumGateOp): string | null {
    switch (gate.type.toUpperCase()) {
      case 'I':
        return `qc.addGate('I', ${gate.qubits[0]});`;
      
      case 'X':
        return `qc.addGate('X', ${gate.qubits[0]});`;
      
      case 'Y':
        return `qc.addGate('Y', ${gate.qubits[0]});`;
      
      case 'Z':
        return `qc.addGate('Z', ${gate.qubits[0]});`;
      
      case 'H':
        return `qc.addGate('H', ${gate.qubits[0]});`;
      
      case 'S':
        return `qc.addGate('S', ${gate.qubits[0]});`;
      
      case 'T':
        return `qc.addGate('T', ${gate.qubits[0]});`;
      
      case 'RX':
        if (gate.angle !== undefined) {
          return `qc.addGate('RX', ${gate.qubits[0]}, ${gate.angle});`;
        }
        break;
      
      case 'RY':
        if (gate.angle !== undefined) {
          return `qc.addGate('RY', ${gate.qubits[0]}, ${gate.angle});`;
        }
        break;
      
      case 'RZ':
        if (gate.angle !== undefined) {
          return `qc.addGate('RZ', ${gate.qubits[0]}, ${gate.angle});`;
        }
        break;
      
      case 'CNOT':
      case 'CX':
        if (gate.qubits.length >= 2) {
          const control = gate.control ?? gate.qubits[0];
          const target = gate.target ?? gate.qubits[1];
          return `qc.cnot(${control}, ${target});`;
        }
        break;
      
      case 'CZ':
        if (gate.qubits.length >= 2) {
          const control = gate.control ?? gate.qubits[0];
          const target = gate.target ?? gate.qubits[1];
          return `qc.addGate('CZ', [${control}, ${target}]);`;
        }
        break;
      
      case 'SWAP':
        if (gate.qubits.length >= 2) {
          return `qc.addGate('SWAP', [${gate.qubits[0]}, ${gate.qubits[1]}]);`;
        }
        break;
      
      case 'TOFFOLI':
      case 'CCX':
        if (gate.qubits.length >= 3) {
          return `qc.addGate('TOFFOLI', [${gate.qubits[0]}, ${gate.qubits[1]}, ${gate.qubits[2]}]);`;
        }
        break;
      
      case 'MEASURE':
        return `qc.measure(${gate.qubits[0]});`;
      
      default:
        console.warn(`Unknown gate type for JS export: ${gate.type}`);
        return `// Unknown gate: ${gate.type}`;
    }

    console.warn(`Invalid gate parameters for ${gate.type}:`, gate);
    return `// Invalid gate: ${gate.type}`;
  }

  // Add visualization code generator
  generateVisualizationCode(): string[] {
    return [
      '',
      'function visualizeResults(result) {',
      '  // Create probability histogram',
      '  const canvas = document.getElementById("quantum-viz");',
      '  if (!canvas) {',
      '    console.warn("Canvas element with id \'quantum-viz\' not found");',
      '    return;',
      '  }',
      '  ',
      '  const ctx = canvas.getContext("2d");',
      '  const probabilities = result.probabilities;',
      '  ',
      '  // Clear canvas',
      '  ctx.clearRect(0, 0, canvas.width, canvas.height);',
      '  ',
      '  // Draw probability bars',
      '  const barWidth = canvas.width / probabilities.length;',
      '  const maxProb = Math.max(...probabilities);',
      '  ',
      '  probabilities.forEach((prob, index) => {',
      '    const barHeight = (prob / maxProb) * canvas.height * 0.8;',
      '    const x = index * barWidth;',
      '    const y = canvas.height - barHeight;',
      '    ',
      '    // Draw bar',
      '    ctx.fillStyle = `hsl(${(index * 360) / probabilities.length}, 70%, 50%)`;',
      '    ctx.fillRect(x + 2, y, barWidth - 4, barHeight);',
      '    ',
      '    // Draw state label',
      '    ctx.fillStyle = "black";',
      '    ctx.font = "12px Arial";',
      '    ctx.textAlign = "center";',
      '    const stateLabel = index.toString(2).padStart(Math.log2(probabilities.length), "0");',
      '    ctx.fillText(`|${stateLabel}⟩`, x + barWidth/2, canvas.height - 5);',
      '  });',
      '}'
    ];
  }

  // Static method for quick export
  static exportToJS(circuit: any, options?: Partial<JSExportOptions>): string {
    const exporter = new EnhancedJavaScriptExporter(options);
    const jsCircuit = EnhancedJavaScriptExporter.fromQOSimCircuit(circuit);
    return exporter.exportCircuit(jsCircuit);
  }

  static fromQOSimCircuit(circuit: any): JSCircuit {
    const gates: QuantumGateOp[] = circuit.gates.map((gate: any, index: number) => ({
      id: gate.id || `gate_${index}`,
      type: gate.type,
      qubits: gate.qubits || [gate.qubit].filter((q: any) => q !== undefined),
      control: gate.control,
      target: gate.target,
      angle: gate.angle,
      params: gate.params,
      position: gate.position || index
    }));

    return {
      name: circuit.name || 'QOSim_Circuit',
      qubits: circuit.qubits?.length || Math.max(...gates.flatMap(g => g.qubits)) + 1,
      gates,
      shots: circuit.shots || 1024
    };
  }
}