
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { UserProfileDropdown } from "@/components/UserProfileDropdown";
import { 
  Activity, 
  Zap, 
  Code, 
  Globe, 
  Users, 
  Star, 
  ArrowRight,
  ChevronRight,
  Github,
  BookOpen,
  Puzzle,
  Cpu,
  MemoryStick,
  FileText,
  Wrench,
  Download,
  Play,
  Microscope,
  Layers,
  Settings,
  Binary,
  Atom,
  Network,
  Shield,
  Sparkles,
  Rocket,
  Target,
  Lightbulb,
  Database,
  Cloud,
  Lock,
  Smartphone,
  MonitorSpeaker,
  Headphones,
  Gamepad2,
  Camera,
  Music,
  Video,
  Image,
  FileCode,
  Terminal,
  Server,
  HardDrive,
  Wifi,
  Bluetooth,
  Usb,
  Printer,
  Scanner,
  Keyboard,
  Mouse,
  Webcam,
  Microphone,
  Speaker,
  Headset,
  Tablet,
  Watch,
  Car,
  Plane,
  Ship,
  Train,
  Bike,
  Bus,
  Taxi,
  Truck,
  Motorcycle,
  Scooter,
  Boat,
  Helicopter,
  Rocket as RocketIcon,
  Satellite,
  Telescope,
  Microscope as MicroscopeIcon,
  Dna,
  Atom as AtomIcon,
  Molecule,
  Beaker,
  TestTube,
  Flask,
  Pipette,
  Syringe,
  Stethoscope,
  Thermometer,
  Scale,
  Calculator,
  Ruler,
  Compass,
  Protractor,
  Eraser,
  Pen,
  Pencil,
  Brush,
  Palette,
  Scissors,
  Paperclip,
  Stapler,
  Folder,
  File,
  FileImage,
  FileVideo,
  FileAudio,
  FileCode as FileCodeIcon,
  Archive,
  Trash,
  Search,
  Filter,
  Sort,
  Grid,
  List,
  BarChart,
  LineChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  DollarSign,
  CreditCard,
  Wallet,
  Coins,
  Banknote,
  Receipt,
  ShoppingCart,
  ShoppingBag,
  Store,
  Building,
  Home,
  MapPin,
  Map,
  Navigation,
  Compass as CompassIcon,
  Flag,
  Clock,
  Calendar,
  Timer,
  Stopwatch,
  Alarm,
  Bell,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Pause,
  Stop,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
  Shuffle,
  Repeat,
  Repeat1,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Share,
  Bookmark,
  Tag,
  Hash,
  AtSign,
  Percent,
  Plus,
  Minus,
  X,
  Check,
  Info,
  AlertCircle,
  AlertTriangle,
  HelpCircle,
  MessageCircle,
  MessageSquare,
  Mail,
  Send,
  Inbox,
  Outbox,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  PhoneMissed,
  Video as VideoIcon,
  Videotape,
  Clapperboard,
  Film,
  Tv,
  Radio,
  Podcast,
  Rss,
  Newspaper,
  Book,
  BookOpen as BookOpenIcon,
  Library,
  GraduationCap,
  Award,
  Medal,
  Trophy,
  Crown,
  Gem,
  Gift,
  PartyPopper,
  Cake,
  Coffee,
  Wine,
  Beer,
  Utensils,
  ChefHat,
  Pizza,
  Hamburger,
  Sandwich,
  Salad,
  Soup,
  IceCream,
  Cookie,
  Donut,
  Candy,
  Lollipop,
  Cherry,
  Apple,
  Banana,
  Orange,
  Grape,
  Strawberry,
  Watermelon,
  Pineapple,
  Coconut,
  Avocado,
  Carrot,
  Tomato,
  Corn,
  Broccoli,
  Lettuce,
  Mushroom,
  Potato,
  Onion,
  Garlic,
  Pepper,
  Chili,
  Herb,
  Flower,
  Rose,
  Tulip,
  Sunflower,
  Daisy,
  Lotus,
  Hibiscus,
  Orchid,
  Lily,
  Jasmine,
  Lavender,
  Rosemary,
  Thyme,
  Sage,
  Mint,
  Basil,
  Parsley,
  Cilantro,
  Dill,
  Oregano,
  Fennel,
  Ginger,
  Turmeric,
  Cinnamon,
  Nutmeg,
  Cloves,
  Cardamom,
  Vanilla,
  Chocolate,
  Honey,
  Maple,
  Sugar,
  Salt,
  Oil,
  Vinegar,
  Soy,
  Fish,
  Meat,
  Chicken,
  Beef,
  Pork,
  Lamb,
  Turkey,
  Duck,
  Goose,
  Rabbit,
  Deer,
  Elk,
  Moose,
  Bear,
  Wolf,
  Fox,
  Raccoon,
  Squirrel,
  Chipmunk,
  Beaver,
  Otter,
  Seal,
  Whale,
  Dolphin,
  Shark,
  Octopus,
  Crab,
  Lobster,
  Shrimp,
  Oyster,
  Clam,
  Mussel,
  Scallop,
  Jellyfish,
  Seahorse,
  Starfish,
  Turtle,
  Frog,
  Toad,
  Salamander,
  Lizard,
  Snake,
  Crocodile,
  Alligator,
  Iguana,
  Chameleon,
  Gecko,
  Skink,
  Monitor,
  Bearded,
  Dragon,
  Komodo,
  Cobra,
  Viper,
  Python,
  Boa,
  Rattlesnake,
  Copperhead,
  Mamba,
  Adder,
  Asp,
  Anaconda,
  Constrictor,
  Coral,
  Milk,
  King,
  Garter,
  Grass,
  Water,
  Sea,
  Tree,
  Rock,
  Sand,
  Desert,
  Forest,
  Jungle,
  Swamp,
  Marsh,
  Wetland,
  Prairie,
  Savanna,
  Grassland,
  Meadow,
  Field,
  Farm,
  Ranch,
  Pasture,
  Orchard,
  Vineyard,
  Garden,
  Park,
  Zoo,
  Aquarium,
  Museum,
  Library as LibraryIcon,
  School,
  University,
  College,
  Hospital,
  Clinic,
  Pharmacy,
  Bank,
  ATM,
  Restaurant,
  Cafe,
  Bar,
  Pub,
  Club,
  Theater,
  Cinema,
  Concert,
  Stadium,
  Arena,
  Gym,
  Pool,
  Spa,
  Salon,
  Barbershop,
  Laundromat,
  Dry,
  Cleaner,
  Tailor,
  Seamstress,
  Cobbler,
  Locksmith,
  Carpenter,
  Plumber,
  Electrician,
  Mechanic,
  Dentist,
  Doctor,
  Nurse,
  Surgeon,
  Veterinarian,
  Pharmacist,
  Optometrist,
  Psychologist,
  Psychiatrist,
  Therapist,
  Counselor,
  Social,
  Worker,
  Teacher,
  Professor,
  Tutor,
  Coach,
  Trainer,
  Instructor,
  Guide,
  Mentor,
  Advisor,
  Consultant,
  Analyst,
  Researcher,
  Scientist,
  Engineer,
  Architect,
  Designer,
  Artist,
  Musician,
  Singer,
  Dancer,
  Actor,
  Actress,
  Director,
  Producer,
  Writer,
  Author,
  Journalist,
  Reporter,
  Editor,
  Photographer,
  Videographer,
  Filmmaker,
  Animator,
  Illustrator,
  Graphic,
  Web,
  Software,
  Developer,
  Programmer,
  Coder,
  Hacker,
  Cybersecurity,
  IT,
  Support,
  Technician,
  Administrator,
  Manager,
  Supervisor,
  CEO,
  President,
  Vice,
  Director as DirectorIcon,
  Officer,
  Executive,
  Assistant,
  Secretary,
  Receptionist,
  Clerk,
  Cashier,
  Salesperson,
  Customer,
  Service,
  Representative,
  Agent,
  Broker,
  Realtor,
  Lawyer,
  Attorney,
  Judge,
  Paralegal,
  Accountant,
  Auditor,
  Bookkeeper,
  Financial,
  Advisor as AdvisorIcon,
  Insurance,
  Actuary,
  Underwriter,
  Claims,
  Adjuster,
  Investigator,
  Detective,
  Police,
  Sheriff,
  Deputy,
  Sergeant,
  Lieutenant,
  Captain,
  Chief,
  Commissioner,
  Marshal,
  Ranger,
  Guard,
  Security,
  Bouncer,
  Bodyguard,
  Firefighter,
  Paramedic,
  EMT,
  Dispatcher,
  Operator,
  Pilot,
  Copilot,
  Flight,
  Attendant,
  Air,
  Traffic,
  Controller,
  Navigator,
  Captain as CaptainIcon,
  First,
  Mate,
  Crew,
  Member,
  Passenger,
  Tourist,
  Traveler,
  Visitor,
  Guest,
  Host,
  Hostess,
  Waiter,
  Waitress,
  Bartender,
  Barista,
  Chef,
  Cook,
  Baker,
  Pastry,
  Butcher,
  Fishmonger,
  Grocer,
  Vendor,
  Merchant,
  Trader,
  Businessman,
  Businesswoman,
  Entrepreneur,
  Investor,
  Shareholder,
  Stockholder,
  Partner,
  Cofounder,
  Founder,
  Owner,
  Boss,
  Leader,
  Chief as ChiefIcon,
  Head,
  Principal,
  Dean,
  Provost,
  Chancellor,
  Rector,
  Superintendent,
  Supervisor as SupervisorIcon,
  Foreman,
  Overseer,
  Coordinator,
  Organizer,
  Planner,
  Scheduler,
  Dispatcher as DispatcherIcon,
  Logistics,
  Supply,
  Chain,
  Procurement,
  Purchasing,
  Buyer,
  Seller,
  Retailer,
  Wholesaler,
  Distributor,
  Supplier,
  Manufacturer,
  Producer as ProducerIcon,
  Factory,
  Plant,
  Mill,
  Refinery,
  Foundry,
  Forge,
  Workshop,
  Studio,
  Office,
  Headquarters,
  Branch,
  Subsidiary,
  Division,
  Department,
  Unit,
  Team,
  Squad,
  Group,
  Committee,
  Board,
  Council,
  Assembly,
  Senate,
  Congress,
  Parliament,
  Government,
  Administration,
  Agency,
  Bureau,
  Ministry,
  Department as DepartmentIcon,
  Office as OfficeIcon,
  Commission,
  Authority,
  Organization,
  Institution,
  Foundation,
  Corporation,
  Company,
  Firm,
  Business,
  Enterprise,
  Venture,
  Startup,
  Unicorn,
  Decacorn,
  Hectocorn,
  Gazelle,
  Zebra,
  Cockroach,
  Camel,
  Elephant,
  Unicorn as UnicornIcon,
  Pegasus,
  Phoenix,
  Dragon as DragonIcon,
  Griffin,
  Sphinx,
  Chimera,
  Hydra,
  Kraken,
  Leviathan,
  Behemoth,
  Titan,
  Giant,
  Colossus,
  Goliath,
  Hercules,
  Atlas,
  Prometheus,
  Zeus,
  Poseidon,
  Hades,
  Apollo,
  Artemis,
  Athena,
  Aphrodite,
  Ares,
  Hephaestus,
  Hermes,
  Dionysus,
  Demeter,
  Hestia,
  Persephone,
  Hera,
  Hebe,
  Iris,
  Hecate,
  Nemesis,
  Nike,
  Tyche,
  Fortuna,
  Fate,
  Destiny,
  Fortune,
  Luck,
  Chance,
  Probability,
  Statistics,
  Data,
  Analytics,
  Metrics,
  KPI,
  Dashboard,
  Report,
  Chart,
  Graph,
  Diagram,
  Blueprint,
  Schematic,
  Plan,
  Design,
  Layout,
  Template,
  Framework,
  Architecture,
  Structure,
  Pattern,
  Model,
  Prototype,
  Mock,
  Wireframe,
  Mockup,
  Concept,
  Idea,
  Vision,
  Mission,
  Goal,
  Objective,
  Strategy,
  Tactic,
  Method,
  Approach,
  Technique,
  Skill,
  Ability,
  Talent,
  Gift,
  Strength,
  Weakness,
  Opportunity,
  Threat,
  Risk,
  Challenge,
  Problem,
  Solution,
  Answer,
  Question,
  Query,
  Request,
  Requirement,
  Specification,
  Standard,
  Guideline,
  Rule,
  Policy,
  Procedure,
  Process,
  Workflow,
  Pipeline,
  Funnel,
  Channel,
  Path,
  Route,
  Journey,
  Experience,
  Adventure,
  Quest,
  Mission as MissionIcon,
  Task,
  Assignment,
  Project,
  Program,
  Initiative,
  Campaign,
  Operation,
  Activity,
  Action,
  Event,
  Occurrence,
  Incident,
  Episode,
  Story,
  Tale,
  Narrative,
  Account,
  Description,
  Explanation,
  Definition,
  Meaning,
  Significance,
  Importance,
  Value,
  Worth,
  Price,
  Cost,
  Expense,
  Budget,
  Finance,
  Money,
  Currency,
  Cash,
  Credit,
  Debit,
  Payment,
  Transaction,
  Transfer,
  Exchange,
  Trade,
  Deal,
  Agreement,
  Contract,
  Pact,
  Treaty,
  Accord,
  Settlement,
  Resolution,
  Compromise,
  Negotiation,
  Discussion,
  Debate,
  Argument,
  Dispute,
  Conflict,
  War,
  Peace,
  Harmony,
  Unity,
  Solidarity,
  Cooperation,
  Collaboration,
  Partnership,
  Alliance,
  Coalition,
  Federation,
  Union,
  League,
  Association,
  Society,
  Community,
  Neighborhood,
  District,
  Region,
  Area,
  Zone,
  Territory,
  Land,
  Country,
  Nation,
  State,
  Province,
  County,
  City,
  Town,
  Village,
  Hamlet,
  Settlement,
  Colony,
  Outpost,
  Base,
  Station,
  Port,
  Harbor,
  Dock,
  Pier,
  Wharf,
  Marina,
  Shipyard,
  Boatyard,
  Dry as DryIcon,
  Dock as DockIcon,
  Slip,
  Berth,
  Mooring,
  Anchorage,
  Roadstead,
  Sound,
  Bay,
  Gulf,
  Strait,
  Channel as ChannelIcon,
  Passage,
  Waterway,
  Canal,
  River,
  Stream,
  Creek,
  Brook,
  Tributary,
  Estuary,
  Delta,
  Mouth,
  Source,
  Spring,
  Well,
  Pond,
  Lake,
  Reservoir,
  Dam,
  Weir,
  Lock,
  Sluice,
  Gate,
  Valve,
  Pipe,
  Tube,
  Hose,
  Cable,
  Wire,
  Cord,
  Rope,
  String,
  Thread,
  Yarn,
  Fiber,
  Fabric,
  Cloth,
  Textile,
  Material,
  Substance,
  Matter,
  Element,
  Compound,
  Mixture,
  Solution,
  Suspension,
  Emulsion,
  Gel,
  Foam,
  Liquid,
  Gas,
  Solid,
  Plasma,
  State,
  Phase,
  Transition,
  Change,
  Transformation,
  Conversion,
  Reaction,
  Process as ProcessIcon,
  Procedure as ProcedureIcon,
  Method as MethodIcon,
  Technique as TechniqueIcon,
  Approach as ApproachIcon,
  Strategy as StrategyIcon,
  Plan as PlanIcon,
  Scheme,
  Plot,
  Design as DesignIcon,
  Blueprint as BlueprintIcon,
  Diagram as DiagramIcon,
  Chart as ChartIcon,
  Graph as GraphIcon,
  Map as MapIcon,
  Atlas as AtlasIcon,
  Guide as GuideIcon,
  Manual,
  Handbook,
  Encyclopedia,
  Dictionary,
  Glossary,
  Index,
  Catalog,
  Directory,
  List as ListIcon,
  Table,
  Schedule,
  Calendar as CalendarIcon,
  Agenda,
  Timeline,
  Chronology,
  History,
  Record,
  Log,
  Journal,
  Diary,
  Note,
  Memo,
  Message,
  Letter,
  Email,
  Text,
  Document,
  Paper,
  Article,
  Essay,
  Report as ReportIcon,
  Study,
  Research,
  Investigation,
  Inquiry,
  Survey,
  Poll,
  Questionnaire,
  Interview,
  Conversation,
  Discussion as DiscussionIcon,
  Talk,
  Speech,
  Presentation,
  Lecture,
  Seminar,
  Workshop as WorkshopIcon,
  Conference,
  Convention,
  Summit,
  Meeting,
  Gathering,
  Assembly as AssemblyIcon,
  Rally,
  Demonstration,
  Protest,
  March,
  Parade,
  Procession,
  Ceremony,
  Ritual,
  Tradition,
  Custom,
  Practice,
  Habit,
  Routine,
  Schedule as ScheduleIcon,
  Agenda as AgendaIcon,
  Program as ProgramIcon,
  Curriculum,
  Course,
  Class,
  Lesson,
  Session,
  Period,
  Term,
  Semester,
  Quarter,
  Year,
  Decade,
  Century,
  Millennium,
  Era,
  Age,
  Epoch,
  Period as PeriodIcon,
  Time,
  Duration,
  Interval,
  Span,
  Range,
  Scope,
  Extent,
  Scale,
  Size,
  Dimension,
  Measurement,
  Unit,
  Standard as StandardIcon,
  Norm,
  Average,
  Mean,
  Median,
  Mode,
  Minimum,
  Maximum,
  Range as RangeIcon,
  Variance,
  Deviation,
  Error,
  Margin,
  Tolerance,
  Precision,
  Accuracy,
  Quality,
  Grade,
  Score,
  Rating,
  Ranking,
  Position,
  Place,
  Spot,
  Location,
  Site,
  Point,
  Coordinate,
  Address,
  Venue,
  Destination,
  Origin,
  Source as SourceIcon,
  Target as TargetIcon,
  Goal as GoalIcon,
  Objective as ObjectiveIcon,
  Purpose,
  Intention,
  Aim,
  Direction,
  Orientation,
  Alignment,
  Focus,
  Concentration,
  Attention,
  Awareness,
  Consciousness,
  Mindfulness,
  Meditation,
  Contemplation,
  Reflection,
  Thought,
  Idea as IdeaIcon,
  Concept as ConceptIcon,
  Notion,
  Understanding,
  Comprehension,
  Knowledge,
  Wisdom,
  Intelligence,
  Insight,
  Intuition,
  Instinct,
  Feeling,
  Emotion,
  Sentiment,
  Mood,
  Attitude,
  Disposition,
  Temperament,
  Personality,
  Character,
  Nature,
  Essence,
  Spirit,
  Soul,
  Mind,
  Brain,
  Consciousness as ConsciousnessIcon,
  Awareness as AwarenessIcon,
  Perception,
  Sensation,
  Experience as ExperienceIcon,
  Memory,
  Recall,
  Recognition,
  Familiarity,
  Acquaintance,
  Friendship,
  Relationship,
  Connection,
  Link,
  Bond,
  Tie,
  Association as AssociationIcon,
  Affiliation,
  Membership,
  Participation,
  Involvement,
  Engagement,
  Commitment,
  Dedication,
  Devotion,
  Loyalty,
  Allegiance,
  Fidelity,
  Faith,
  Trust,
  Confidence,
  Assurance,
  Certainty,
  Conviction,
  Belief,
  Opinion,
  View,
  Perspective,
  Standpoint,
  Position as PositionIcon,
  Stance,
  Attitude as AttitudeIcon,
  Approach as ApproachIcon2,
  Method as MethodIcon2,
  Way,
  Manner,
  Style,
  Fashion,
  Trend,
  Pattern as PatternIcon,
  Rhythm,
  Beat,
  Tempo,
  Pace,
  Speed,
  Rate,
  Frequency,
  Wavelength,
  Amplitude,
  Phase as PhaseIcon,
  Cycle,
  Loop,
  Iteration,
  Repetition,
  Recurrence,
  Return,
  Comeback,
  Revival,
  Renaissance,
  Rebirth,
  Renewal,
  Restoration,
  Recovery,
  Healing,
  Cure,
  Treatment,
  Therapy,
  Medicine,
  Drug,
  Medication,
  Prescription,
  Dose,
  Dosage,
  Administration,
  Application,
  Usage,
  Utilization,
  Employment,
  Deployment,
  Implementation,
  Execution,
  Performance,
  Operation as OperationIcon,
  Function,
  Functionality,
  Feature,
  Capability,
  Capacity,
  Potential,
  Possibility,
  Opportunity as OpportunityIcon,
  Chance as ChanceIcon,
  Probability as ProbabilityIcon,
  Likelihood,
  Risk as RiskIcon,
  Danger,
  Hazard,
  Threat as ThreatIcon,
  Menace,
  Peril,
  Jeopardy,
  Vulnerability,
  Weakness as WeaknessIcon,
  Flaw,
  Defect,
  Fault,
  Error as ErrorIcon,
  Mistake,
  Blunder,
  Slip,
  Oversight,
  Omission,
  Negligence,
  Carelessness,
  Recklessness,
  Imprudence,
  Indiscretion,
  Misjudgment,
  Miscalculation,
  Misunderstanding,
  Confusion,
  Ambiguity,
  Uncertainty,
  Doubt,
  Skepticism,
  Suspicion,
  Distrust,
  Mistrust,
  Disbelief,
  Incredulity,
  Amazement,
  Astonishment,
  Wonder,
  Awe,
  Reverence,
  Respect,
  Admiration,
  Appreciation,
  Gratitude,
  Thankfulness,
  Recognition as RecognitionIcon,
  Acknowledgment,
  Praise,
  Compliment,
  Flattery,
  Adulation,
  Worship,
  Idolatry,
  Devotion as DevotionIcon,
  Love,
  Affection,
  Fondness,
  Liking,
  Preference,
  Favor,
  Partiality,
  Bias,
  Prejudice,
  Discrimination,
  Inequality,
  Injustice,
  Unfairness,
  Imbalance,
  Disparity,
  Difference,
  Distinction,
  Contrast,
  Comparison,
  Similarity,
  Resemblance,
  Likeness,
  Analogy,
  Metaphor,
  Symbolism,
  Representation,
  Depiction,
  Illustration,
  Visualization,
  Imagery,
  Picture,
  Painting,
  Drawing,
  Sketch,
  Diagram as DiagramIcon2,
  Chart as ChartIcon2,
  Graph as GraphIcon2,
  Plot as PlotIcon,
  Map as MapIcon2,
  Blueprint as BlueprintIcon2,
  Plan as PlanIcon2,
  Design as DesignIcon2,
  Layout as LayoutIcon,
  Structure as StructureIcon,
  Framework as FrameworkIcon,
  Architecture as ArchitectureIcon,
  System,
  Network as NetworkIcon,
  Web as WebIcon,
  Internet,
  Online,
  Digital,
  Electronic,
  Virtual,
  Cyber,
  Tech,
  Technology,
  Innovation,
  Invention,
  Discovery,
  Breakthrough,
  Advancement,
  Progress,
  Development,
  Evolution,
  Growth,
  Expansion,
  Extension,
  Enlargement,
  Increase,
  Rise,
  Elevation,
  Improvement,
  Enhancement,
  Upgrade,
  Update,
  Modification,
  Alteration,
  Change as ChangeIcon,
  Transformation as TransformationIcon,
  Metamorphosis,
  Transition as TransitionIcon,
  Shift,
  Move,
  Movement,
  Motion,
  Activity as ActivityIcon,
  Action as ActionIcon,
  Behavior,
  Conduct,
  Performance as PerformanceIcon,
  Execution as ExecutionIcon,
  Implementation as ImplementationIcon,
  Deployment as DeploymentIcon,
  Launch,
  Start,
  Beginning,
  Initiation,
  Commencement,
  Opening,
  Inauguration,
  Premiere,
  Debut,
  Introduction,
  Presentation as PresentationIcon,
  Demonstration as DemonstrationIcon,
  Exhibition,
  Display,
  Show,
  Performance as PerformanceIcon2,
  Act,
  Scene,
  Episode as EpisodeIcon,
  Chapter,
  Section,
  Part,
  Segment,
  Division as DivisionIcon,
  Category,
  Classification,
  Type,
  Kind,
  Sort,
  Variety,
  Species,
  Genus,
  Family,
  Order,
  Class as ClassIcon,
  Phylum,
  Kingdom,
  Domain,
  Realm,
  Sphere,
  Field,
  Area as AreaIcon,
  Zone as ZoneIcon,
  Region as RegionIcon,
  Territory as TerritoryIcon,
  Land as LandIcon,
  Ground,
  Soil,
  Earth,
  Planet,
  World,
  Globe as GlobeIcon,
  Universe,
  Cosmos,
  Space,
  Void,
  Vacuum,
  Emptiness,
  Nothingness,
  Absence,
  Lack,
  Shortage,
  Deficit,
  Scarcity,
  Rarity,
  Uniqueness,
  Singularity,
  Individuality,
  Personality as PersonalityIcon,
  Identity,
  Self,
  Ego,
  Consciousness as ConsciousnessIcon2,
  Awareness as AwarenessIcon2,
  Perception as PerceptionIcon,
  Sensation as SensationIcon,
  Feeling as FeelingIcon,
  Emotion as EmotionIcon,
  Sentiment as SentimentIcon,
  Mood as MoodIcon,
  Atmosphere,
  Environment,
  Setting,
  Context,
  Situation,
  Circumstance,
  Condition,
  State as StateIcon,
  Status,
  Position as PositionIcon2,
  Rank,
  Level,
  Grade as GradeIcon,
  Degree,
  Extent as ExtentIcon,
  Scope as ScopeIcon,
  Range as RangeIcon2,
  Span as SpanIcon,
  Duration as DurationIcon,
  Length,
  Width,
  Height,
  Depth,
  Thickness,
  Breadth,
  Diameter,
  Radius,
  Circumference,
  Perimeter,
  Area as AreaIcon2,
  Surface,
  Volume,
  Capacity as CapacityIcon,
  Size as SizeIcon,
  Scale as ScaleIcon,
  Proportion,
  Ratio,
  Percentage,
  Fraction,
  Decimal,
  Number,
  Digit,
  Figure,
  Numeral,
  Count,
  Quantity,
  Amount,
  Sum,
  Total,
  Aggregate,
  Accumulation,
  Collection,
  Compilation,
  Assembly as AssemblyIcon2,
  Gathering as GatheringIcon,
  Group as GroupIcon,
  Set,
  Series,
  Sequence,
  Order as OrderIcon,
  Arrangement,
  Organization as OrganizationIcon,
  Structure as StructureIcon2,
  System as SystemIcon,
  Framework as FrameworkIcon2,
  Architecture as ArchitectureIcon2,
  Design as DesignIcon3,
  Pattern as PatternIcon2,
  Template as TemplateIcon,
  Model as ModelIcon,
  Example,
  Instance,
  Case,
  Sample,
  Specimen,
  Test,
  Trial,
  Experiment,
  Research as ResearchIcon,
  Study as StudyIcon,
  Investigation as InvestigationIcon,
  Analysis,
  Examination,
  Inspection,
  Review,
  Assessment,
  Evaluation,
  Appraisal,
  Judgment,
  Decision,
  Choice,
  Selection,
  Option,
  Alternative,
  Possibility as PossibilityIcon,
  Scenario,
  Situation as SituationIcon,
  Case as CaseIcon,
  Circumstance as CircumstanceIcon,
  Condition as ConditionIcon,
  Requirement as RequirementIcon,
  Prerequisite,
  Necessity,
  Need,
  Want,
  Desire,
  Wish,
  Hope,
  Expectation,
  Anticipation,
  Prediction,
  Forecast,
  Projection,
  Estimation,
  Calculation,
  Computation,
  Processing,
  Transformation as TransformationIcon2,
  Conversion as ConversionIcon,
  Translation,
  Interpretation,
  Explanation as ExplanationIcon,
  Clarification,
  Elucidation,
  Illumination,
  Enlightenment,
  Understanding as UnderstandingIcon,
  Comprehension as ComprehensionIcon,
  Knowledge as KnowledgeIcon,
  Information,
  Data as DataIcon,
  Facts,
  Evidence,
  Proof,
  Verification,
  Confirmation,
  Validation,
  Authentication,
  Authorization,
  Permission,
  Approval,
  Consent,
  Agreement as AgreementIcon,
  Acceptance,
  Acknowledgment as AcknowledgmentIcon,
  Recognition as RecognitionIcon2,
  Admission,
  Confession,
  Declaration,
  Statement,
  Announcement,
  Proclamation,
  Notification,
  Alert,
  Warning,
  Caution,
  Advice,
  Guidance,
  Direction as DirectionIcon,
  Instruction,
  Command,
  Order as OrderIcon2,
  Request as RequestIcon,
  Demand,
  Requirement as RequirementIcon2,
  Specification as SpecificationIcon,
  Description as DescriptionIcon,
  Definition as DefinitionIcon,
  Meaning as MeaningIcon,
  Significance as SignificanceIcon,
  Importance as ImportanceIcon,
  Relevance,
  Applicability,
  Suitability,
  Appropriateness,
  Fitness,
  Compatibility,
  Consistency,
  Coherence,
  Logic,
  Reasoning,
  Rationale,
  Justification,
  Explanation as ExplanationIcon2,
  Reason,
  Cause,
  Factor,
  Element as ElementIcon,
  Component,
  Ingredient,
  Constituent,
  Part as PartIcon,
  Piece,
  Fragment,
  Portion,
  Section as SectionIcon,
  Segment as SegmentIcon,
  Division as DivisionIcon2,
  Subdivision,
  Branch as BranchIcon,
  Department as DepartmentIcon2,
  Unit as UnitIcon,
  Module,
  Block,
  Chunk,
  Bit,
  Byte,
  Kilobyte,
  Megabyte,
  Gigabyte,
  Terabyte,
  Petabyte,
  Exabyte,
  Zettabyte,
  Yottabyte,
  Pixel,
  Resolution,
  Quality as QualityIcon,
  Clarity,
  Sharpness,
  Focus as FocusIcon,
  Depth as DepthIcon,
  Perspective as PerspectiveIcon,
  Viewpoint,
  Angle,
  Aspect,
  Facet,
  Side,
  Face,
  Front,
  Back,
  Top,
  Bottom,
  Left,
  Right,
  Up,
  Down,
  In,
  Out,
  Inside,
  Outside,
  Interior,
  Exterior,
  Internal,
  External,
  Public,
  Private,
  Personal,
  Individual,
  Collective,
  Common,
  Shared,
  Joint,
  Mutual,
  Reciprocal,
  Bilateral,
  Multilateral,
  Universal,
  Global,
  International,
  National,
  Regional,
  Local,
  Domestic,
  Foreign,
  Alien,
  Strange,
  Weird,
  Odd,
  Unusual,
  Abnormal,
  Extraordinary,
  Remarkable,
  Notable,
  Significant,
  Important,
  Major,
  Minor,
  Primary,
  Secondary,
  Tertiary,
  Quaternary,
  First,
  Second,
  Third,
  Fourth,
  Fifth,
  Sixth,
  Seventh,
  Eighth,
  Ninth,
  Tenth,
  Last,
  Final,
  Ultimate,
  Conclusive,
  Decisive,
  Definitive,
  Absolute,
  Complete,
  Total,
  Whole,
  Entire,
  Full,
  Partial,
  Incomplete,
  Unfinished,
  Ongoing,
  Continuous,
  Constant,
  Steady,
  Stable,
  Fixed,
  Static,
  Dynamic,
  Active,
  Passive,
  Reactive,
  Responsive,
  Sensitive,
  Aware,
  Conscious,
  Alert,
  Vigilant,
  Watchful,
  Observant,
  Attentive,
  Focused,
  Concentrated,
  Intense,
  Strong,
  Powerful,
  Forceful,
  Vigorous,
  Energetic,
  Lively,
  Animated,
  Spirited,
  Enthusiastic,
  Passionate,
  Fervent,
  Zealous,
  Eager,
  Keen,
  Interested,
  Curious,
  Inquisitive,
  Investigative,
  Exploratory,
  Experimental,
  Innovative,
  Creative,
  Imaginative,
  Inventive,
  Original,
  Unique,
  Distinctive,
  Special,
  Exceptional,
  Outstanding,
  Excellent,
  Superior,
  Premium,
  High,
  Top,
  Best,
  Finest,
  Perfect,
  Ideal,
  Optimal,
  Maximum,
  Peak,
  Summit,
  Apex,
  Pinnacle,
  Crown,
  Top,
  Head,
  Chief,
  Leader,
  Boss,
  Manager,
  Director,
  CEO,
  President,
  Chairman,
  Chairwoman,
  Chairperson,
  Vice,
  Deputy,
  Assistant,
  Associate,
  Partner,
  Colleague,
  Coworker,
  Teammate,
  Member,
  Participant,
  Contributor,
  Collaborator,
  Cooperator,
  Ally,
  Friend,
  Companion,
  Buddy,
  Pal,
  Mate,
  Peer,
  Equal,
  Equivalent,
  Similar,
  Alike,
  Comparable,
  Analogous,
  Parallel,
  Corresponding,
  Matching,
  Identical,
  Same,
  Uniform,
  Consistent,
  Regular,
  Standard,
  Normal,
  Typical,
  Ordinary,
  Common,
  Usual,
  Routine,
  Habitual,
  Customary,
  Traditional,
  Conventional,
  Classical,
  Formal,
  Official,
  Legitimate,
  Legal,
  Lawful,
  Valid,
  Authentic,
  Genuine,
  Real,
  True,
  Actual,
  Factual,
  Concrete,
  Tangible,
  Physical,
  Material,
  Substantial,
  Solid,
  Firm,
  Hard,
  Rigid,
  Stiff,
  Tough,
  Durable,
  Lasting,
  Permanent,
  Eternal,
  Infinite,
  Endless,
  Limitless,
  Boundless,
  Vast,
  Huge,
  Enormous,
  Massive,
  Giant,
  Gigantic,
  Colossal,
  Tremendous,
  Immense,
  Extensive,
  Broad,
  Wide,
  Large,
  Big,
  Great,
  Grand,
  Magnificent,
  Splendid,
  Glorious,
  Wonderful,
  Marvelous,
  Amazing,
  Incredible,
  Unbelievable,
  Fantastic,
  Fabulous,
  Terrific,
  Excellent,
  Outstanding,
  Superb,
  Brilliant,
  Genius,
  Brilliant,
  Smart,
  Intelligent,
  Clever,
  Wise,
  Knowledgeable,
  Educated,
  Learned,
  Scholarly,
  Academic,
  Intellectual,
  Thoughtful,
  Reflective,
  Contemplative,
  Meditative,
  Mindful,
  Aware,
  Conscious,
  Awake,
  Alert,
  Vigilant,
  Watchful,
  Observant,
  Perceptive,
  Insightful,
  Intuitive,
  Instinctive,
  Natural,
  Innate,
  Inherent,
  Built,
  Integrated,
  Embedded,
  Incorporated,
  Included,
  Contained,
  Comprised,
  Composed,
  Made,
  Created,
  Formed,
  Shaped,
  Molded,
  Crafted,
  Built,
  Constructed,
  Assembled,
  Manufactured,
  Produced,
  Generated,
  Developed,
  Evolved,
  Grown,
  Expanded,
  Extended,
  Enlarged,
  Increased,
  Enhanced,
  Improved,
  Upgraded,
  Updated,
  Modified,
  Altered,
  Changed,
  Transformed,
  Converted,
  Adapted,
  Adjusted,
  Tuned,
  Calibrated,
  Optimized,
  Refined,
  Polished,
  Perfected,
  Completed,
  Finished,
  Done,
  Accomplished,
  Achieved,
  Attained,
  Reached,
  Arrived,
  Landed,
  Settled,
  Established,
  Founded,
  Started,
  Launched,
  Initiated,
  Begun,
  Commenced,
  Opened,
  Unveiled,
  Revealed,
  Disclosed,
  Exposed,
  Shown,
  Displayed,
  Exhibited,
  Presented,
  Introduced,
  Announced,
  Proclaimed,
  Declared,
  Stated,
  Said,
  Spoken,
  Uttered,
  Voiced,
  Expressed,
  Communicated,
  Conveyed,
  Transmitted,
  Sent,
  Delivered,
  Transported,
  Moved,
  Shifted,
  Transferred,
  Relocated,
  Placed,
  Positioned,
  Situated,
  Located,
  Found,
  Discovered,
  Identified,
  Recognized,
  Acknowledged,
  Accepted,
  Approved,
  Endorsed,
  Supported,
  Backed,
  Sponsored,
  Funded,
  Financed,
  Invested,
  Purchased,
  Bought,
  Acquired,
  Obtained,
  Gained,
  Earned,
  Won,
  Achieved,
  Accomplished,
  Completed,
  Finished,
  Done,
  Over,
  Ended,
  Concluded,
  Closed,
  Shut,
  Sealed,
  Locked,
  Secured,
  Protected,
  Guarded,
  Defended,
  Shielded,
  Covered,
  Hidden,
  Concealed,
  Obscured,
  Masked,
  Veiled,
  Shrouded,
  Wrapped,
  Enclosed,
  Surrounded,
  Encircled,
  Encompassed,
  Embraced,
  Hugged,
  Held,
  Grasped,
  Gripped,
  Clutched,
  Seized,
  Caught,
  Captured,
  Trapped,
  Snared,
  Ensnared,
  Entangled,
  Tangled,
  Twisted,
  Wound,
  Coiled,
  Curled,
  Curved,
  Bent,
  Arched,
  Bowed,
  Flexed,
  Stretched,
  Extended,
  Reached,
  Touched,
  Felt,
  Sensed,
  Perceived,
  Noticed,
  Observed,
  Watched,
  Seen,
  Viewed,
  Looked,
  Gazed,
  Stared,
  Glanced,
  Peeked,
  Peered,
  Scrutinized,
  Examined,
  Inspected,
  Studied,
  Analyzed,
  Evaluated,
  Assessed,
  Judged,
  Decided,
  Determined,
  Resolved,
  Settled,
  Concluded,
  Finished,
  Ended,
  Stopped,
  Ceased,
  Halted,
  Paused,
  Suspended,
  Interrupted,
  Broken,
  Disrupted,
  Disturbed,
  Interfered,
  Hindered,
  Blocked,
  Obstructed,
  Impeded,
  Prevented,
  Stopped,
  Avoided,
  Evaded,
  Escaped,
  Fled,
  Ran,
  Rushed,
  Hurried,
  Sped,
  Accelerated,
  Quickened,
  Hastened,
  Expedited,
  Facilitated,
  Enabled,
  Allowed,
  Permitted,
  Authorized,
  Approved,
  Granted,
  Given,
  Provided,
  Supplied,
  Furnished,
  Delivered,
  Offered,
  Presented,
  Shown,
  Displayed,
  Exhibited,
  Demonstrated,
  Illustrated,
  Depicted,
  Portrayed,
  Represented,
  Symbolized,
  Signified,
  Indicated,
  Pointed,
  Directed,
  Guided,
  Led,
  Conducted,
  Managed,
  Controlled,
  Governed,
  Ruled,
  Commanded,
  Ordered,
  Instructed,
  Taught,
  Educated,
  Trained,
  Coached,
  Mentored,
  Advised,
  Counseled,
  Guided,
  Helped,
  Assisted,
  Supported,
  Aided,
  Served,
  Attended,
  Cared,
  Nursed,
  Treated,
  Healed,
  Cured,
  Fixed,
  Repaired,
  Restored,
  Recovered,
  Regained,
  Retrieved,
  Reclaimed,
  Recaptured,
  Retaken,
  Returned,
  Came,
  Arrived,
  Reached,
  Attained,
  Achieved,
  Accomplished,
  Completed,
  Finished,
  Done,
  Made,
  Created,
  Formed,
  Built,
  Constructed,
  Assembled,
  Manufactured,
  Produced,
  Generated,
  Developed,
  Evolved,
  Grown,
  Expanded,
  Extended,
  Enlarged,
  Increased,
  Enhanced,
  Improved,
  Upgraded,
  Updated,
  Modified,
  Altered,
  Changed,
  Transformed,
  Converted,
  Adapted,
  Adjusted,
  Tuned,
  Calibrated,
  Optimized,
  Refined,
  Polished,
  Perfected
} from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";

const Index = () => {
  const navigate = useNavigate();
  const { user } = useAuth();

  const handleGetStarted = () => {
    if (user) {
      navigate('/app');
    } else {
      navigate('/auth');
    }
  };

  const features = [
    {
      icon: <Cpu className="w-12 h-12 text-quantum-glow" />,
      title: "Quantum Circuit Builder",
      description: "Visual drag-and-drop interface for creating quantum circuits with real-time simulation"
    },
    {
      icon: <Code className="w-12 h-12 text-quantum-glow" />,
      title: "Multi-Language SDK",
      description: "Python, JavaScript, and C++ SDKs with comprehensive quantum algorithm libraries"
    },
    {
      icon: <Globe className="w-12 h-12 text-quantum-glow" />,
      title: "Hardware Integration",
      description: "Connect to IBM Quantum, Google Cirq, and other quantum hardware platforms"
    },
    {
      icon: <Users className="w-12 h-12 text-quantum-glow" />,
      title: "Collaborative Development",
      description: "Real-time collaboration tools for quantum computing teams and researchers"
    }
  ];

  const algorithms = [
    { name: "Grover's Search", description: "Quantum search algorithm", icon: <Search className="w-6 h-6" /> },
    { name: "Shor's Algorithm", description: "Integer factorization", icon: <Calculator className="w-6 h-6" /> },
    { name: "Quantum Fourier Transform", description: "Frequency analysis", icon: <Zap className="w-6 h-6" /> },
    { name: "Variational Quantum Eigensolver", description: "Optimization problems", icon: <Target className="w-6 h-6" /> }
  ];

  const integrations = [
    { name: "IBM Quantum", logo: <Cpu className="w-8 h-8" /> },
    { name: "Google Cirq", logo: <Globe className="w-8 h-8" /> },
    { name: "Microsoft Azure", logo: <Cloud className="w-8 h-8" /> },
    { name: "Amazon Braket", logo: <Database className="w-8 h-8" /> }
  ];

  return (
    <div className="min-h-screen bg-quantum-void">
      {/* Header */}
      <header className="border-b border-quantum-matrix bg-quantum-void/95 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Activity className="w-8 h-8 text-quantum-glow particle-animation" />
              <h1 className="text-2xl font-bold text-quantum-glow">Quantum OS</h1>
            </div>
            <nav className="hidden md:flex items-center gap-6">
              <Link to="/tutorials" className="text-quantum-neon hover:text-quantum-glow transition-colors">
                Tutorials
              </Link>
              <Link to="/sdk" className="text-quantum-neon hover:text-quantum-glow transition-colors">
                SDK
              </Link>
              <Link to="/api" className="text-quantum-neon hover:text-quantum-glow transition-colors">
                API
              </Link>
              <Link to="/roadmap" className="text-quantum-neon hover:text-quantum-glow transition-colors">
                Roadmap
              </Link>
            </nav>
            <div className="flex items-center gap-4">
              <UserProfileDropdown />
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-20 px-4">
        <div className="container mx-auto text-center">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-5xl md:text-6xl font-bold mb-6 text-quantum-glow">
              The Future of
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-quantum-glow to-quantum-neon">
                {" "}Quantum Computing
              </span>
            </h2>
            <p className="text-xl md:text-2xl mb-8 text-quantum-neon font-mono">
              Build, simulate, and deploy quantum circuits with our comprehensive development platform
            </p>
            <div className="flex flex-col md:flex-row gap-4 justify-center">
              <Button
                size="lg"
                onClick={handleGetStarted}
                className="bg-quantum-glow hover:bg-quantum-glow/80 text-quantum-void font-semibold"
              >
                <Play className="w-5 h-5 mr-2" />
                Get Started
              </Button>
              <Button
                variant="outline"
                size="lg"
                className="border-quantum-matrix hover:bg-quantum-matrix text-quantum-neon"
              >
                <BookOpen className="w-5 h-5 mr-2" />
                Documentation
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4">
        <div className="container mx-auto">
          <div className="text-center mb-16">
            <h3 className="text-3xl md:text-4xl font-bold mb-4 text-quantum-glow">
              Powerful Features
            </h3>
            <p className="text-quantum-neon text-lg max-w-2xl mx-auto">
              Everything you need to develop quantum applications in one integrated platform
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="quantum-panel border-quantum-matrix">
                <CardHeader className="text-center">
                  <div className="flex justify-center mb-4">
                    {feature.icon}
                  </div>
                  <CardTitle className="text-quantum-glow">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-quantum-neon">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Quick Start Section */}
      <section className="py-20 px-4 bg-quantum-matrix/10">
        <div className="container mx-auto">
          <div className="text-center mb-16">
            <h3 className="text-3xl md:text-4xl font-bold mb-4 text-quantum-glow">
              Quick Start
            </h3>
            <p className="text-quantum-neon text-lg max-w-2xl mx-auto">
              Get up and running with quantum computing in minutes
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            <Card className="quantum-panel border-quantum-matrix">
              <CardHeader>
                <div className="flex items-center gap-3">
                  <Badge className="bg-quantum-glow text-quantum-void">1</Badge>
                  <CardTitle className="text-quantum-glow">Create Account</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-quantum-neon mb-4">Sign up for free and access the quantum development environment</p>
                <Button
                  variant="outline"
                  className="w-full border-quantum-matrix hover:bg-quantum-matrix"
                  onClick={() => navigate('/auth')}
                >
                  Sign Up Now
                </Button>
              </CardContent>
            </Card>

            <Card className="quantum-panel border-quantum-matrix">
              <CardHeader>
                <div className="flex items-center gap-3">
                  <Badge className="bg-quantum-glow text-quantum-void">2</Badge>
                  <CardTitle className="text-quantum-glow">Build Circuit</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-quantum-neon mb-4">Use our visual circuit builder to create your first quantum program</p>
                <Button
                  variant="outline"
                  className="w-full border-quantum-matrix hover:bg-quantum-matrix"
                  onClick={() => navigate('/circuit-builder')}
                >
                  Try Circuit Builder
                </Button>
              </CardContent>
            </Card>

            <Card className="quantum-panel border-quantum-matrix">
              <CardHeader>
                <div className="flex items-center gap-3">
                  <Badge className="bg-quantum-glow text-quantum-void">3</Badge>
                  <CardTitle className="text-quantum-glow">Run Simulation</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-quantum-neon mb-4">Execute your quantum circuits with our high-performance simulator</p>
                <Button
                  variant="outline"
                  className="w-full border-quantum-matrix hover:bg-quantum-matrix"
                  onClick={() => navigate('/tutorials')}
                >
                  Learn More
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Algorithms Section */}
      <section className="py-20 px-4">
        <div className="container mx-auto">
          <div className="text-center mb-16">
            <h3 className="text-3xl md:text-4xl font-bold mb-4 text-quantum-glow">
              Quantum Algorithms
            </h3>
            <p className="text-quantum-neon text-lg max-w-2xl mx-auto">
              Pre-built implementations of famous quantum algorithms
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {algorithms.map((algorithm, index) => (
              <Card key={index} className="quantum-panel border-quantum-matrix hover:border-quantum-glow/50 transition-colors">
                <CardHeader>
                  <div className="flex items-center gap-3">
                    <div className="text-quantum-glow">{algorithm.icon}</div>
                    <CardTitle className="text-sm text-quantum-glow">{algorithm.name}</CardTitle>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-quantum-neon text-sm">{algorithm.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Integrations Section */}
      <section className="py-20 px-4 bg-quantum-matrix/10">
        <div className="container mx-auto">
          <div className="text-center mb-16">
            <h3 className="text-3xl md:text-4xl font-bold mb-4 text-quantum-glow">
              Hardware Integrations
            </h3>
            <p className="text-quantum-neon text-lg max-w-2xl mx-auto">
              Connect to leading quantum hardware providers
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {integrations.map((integration, index) => (
              <Card key={index} className="quantum-panel border-quantum-matrix hover:border-quantum-glow/50 transition-colors">
                <CardContent className="p-6 text-center">
                  <div className="text-quantum-glow mb-3 flex justify-center">
                    {integration.logo}
                  </div>
                  <h4 className="text-quantum-glow font-semibold">{integration.name}</h4>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4">
        <div className="container mx-auto text-center">
          <div className="max-w-3xl mx-auto">
            <h3 className="text-3xl md:text-4xl font-bold mb-6 text-quantum-glow">
              Ready to Enter the Quantum Realm?
            </h3>
            <p className="text-xl mb-8 text-quantum-neon">
              Join thousands of developers and researchers building the future of computing
            </p>
            <div className="flex flex-col md:flex-row gap-4 justify-center">
              <Button
                size="lg"
                onClick={handleGetStarted}
                className="bg-quantum-glow hover:bg-quantum-glow/80 text-quantum-void font-semibold"
              >
                <Rocket className="w-5 h-5 mr-2" />
                Start Building
              </Button>
              <Button
                variant="outline"
                size="lg"
                className="border-quantum-matrix hover:bg-quantum-matrix text-quantum-neon"
              >
                <Github className="w-5 h-5 mr-2" />
                View on GitHub
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-quantum-matrix py-12 px-4">
        <div className="container mx-auto">
          <div className="grid md:grid-cols-4 gap-8">
            <div>
              <div className="flex items-center gap-3 mb-4">
                <Activity className="w-6 h-6 text-quantum-glow" />
                <h4 className="text-quantum-glow font-semibold">Quantum OS</h4>
              </div>
              <p className="text-quantum-neon text-sm">
                The comprehensive platform for quantum computing development and research.
              </p>
            </div>
            <div>
              <h5 className="text-quantum-glow font-semibold mb-3">Product</h5>
              <ul className="space-y-2">
                <li><Link to="/circuit-builder" className="text-quantum-neon hover:text-quantum-glow text-sm">Circuit Builder</Link></li>
                <li><Link to="/sdk" className="text-quantum-neon hover:text-quantum-glow text-sm">SDK</Link></li>
                <li><Link to="/api" className="text-quantum-neon hover:text-quantum-glow text-sm">API</Link></li>
              </ul>
            </div>
            <div>
              <h5 className="text-quantum-glow font-semibold mb-3">Resources</h5>
              <ul className="space-y-2">
                <li><Link to="/tutorials" className="text-quantum-neon hover:text-quantum-glow text-sm">Tutorials</Link></li>
                <li><Link to="/roadmap" className="text-quantum-neon hover:text-quantum-glow text-sm">Roadmap</Link></li>
                <li><Link to="/integrations" className="text-quantum-neon hover:text-quantum-glow text-sm">Integrations</Link></li>
              </ul>
            </div>
            <div>
              <h5 className="text-quantum-glow font-semibold mb-3">Community</h5>
              <ul className="space-y-2">
                <li><a href="#" className="text-quantum-neon hover:text-quantum-glow text-sm">Discord</a></li>
                <li><a href="#" className="text-quantum-neon hover:text-quantum-glow text-sm">GitHub</a></li>
                <li><a href="#" className="text-quantum-neon hover:text-quantum-glow text-sm">Documentation</a></li>
              </ul>
            </div>
          </div>
          <Separator className="my-8 bg-quantum-matrix" />
          <div className="text-center text-quantum-neon text-sm">
            <p>&copy; 2024 Quantum OS. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Index;
