
import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Download, Copy, Check } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface Gate {
  id: string;
  type: string;
  qubit: number;
  position: number;
  angle?: number;
  controlQubit?: number;
}

interface Circuit {
  id: string;
  name: string;
  gates: Gate[];
  qubits: number;
  modified: boolean;
}

interface CircuitExporterProps {
  circuit: Circuit;
  onClose: () => void;
  onExport: (format: string) => void;
}

export function CircuitExporter({ circuit, onClose, onExport }: CircuitExporterProps) {
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);
  const { toast } = useToast();

  const generateQASM = () => {
    let qasm = `OPENQASM 2.0;\ninclude "qelib1.inc";\n\n`;
    qasm += `qreg q[${circuit.qubits}];\n`;
    qasm += `creg c[${circuit.qubits}];\n\n`;
    
    const sortedGates = [...circuit.gates].sort((a, b) => a.position - b.position);
    
    sortedGates.forEach(gate => {
      switch (gate.type) {
        case 'H': qasm += `h q[${gate.qubit}];\n`; break;
        case 'X': qasm += `x q[${gate.qubit}];\n`; break;
        case 'Y': qasm += `y q[${gate.qubit}];\n`; break;
        case 'Z': qasm += `z q[${gate.qubit}];\n`; break;
        case 'S': qasm += `s q[${gate.qubit}];\n`; break;
        case 'T': qasm += `t q[${gate.qubit}];\n`; break;
        case 'RX': qasm += `rx(${gate.angle || 'pi/2'}) q[${gate.qubit}];\n`; break;
        case 'RY': qasm += `ry(${gate.angle || 'pi/2'}) q[${gate.qubit}];\n`; break;
        case 'RZ': qasm += `rz(${gate.angle || 'pi/2'}) q[${gate.qubit}];\n`; break;
        case 'CNOT': 
          if (gate.controlQubit !== undefined) {
            qasm += `cx q[${gate.controlQubit}],q[${gate.qubit}];\n`;
          }
          break;
        case 'CZ':
          if (gate.controlQubit !== undefined) {
            qasm += `cz q[${gate.controlQubit}],q[${gate.qubit}];\n`;
          }
          break;
        case 'M': qasm += `measure q[${gate.qubit}] -> c[${gate.qubit}];\n`; break;
      }
    });
    
    return qasm;
  };

  const generateJSON = () => {
    return JSON.stringify({
      name: circuit.name,
      qubits: circuit.qubits,
      gates: circuit.gates.map(gate => ({
        type: gate.type,
        qubit: gate.qubit,
        position: gate.position,
        ...(gate.angle && { angle: gate.angle }),
        ...(gate.controlQubit !== undefined && { controlQubit: gate.controlQubit })
      }))
    }, null, 2);
  };

  const generatePython = () => {
    let python = `# Quantum Circuit: ${circuit.name}\n`;
    python += `# Generated by QOSim\n\n`;
    python += `from qiskit import QuantumCircuit, execute, Aer\n`;
    python += `from qiskit.visualization import plot_histogram\n\n`;
    python += `# Create quantum circuit\n`;
    python += `qc = QuantumCircuit(${circuit.qubits}, ${circuit.qubits})\n\n`;
    
    const sortedGates = [...circuit.gates].sort((a, b) => a.position - b.position);
    
    sortedGates.forEach(gate => {
      switch (gate.type) {
        case 'H': python += `qc.h(${gate.qubit})\n`; break;
        case 'X': python += `qc.x(${gate.qubit})\n`; break;
        case 'Y': python += `qc.y(${gate.qubit})\n`; break;
        case 'Z': python += `qc.z(${gate.qubit})\n`; break;
        case 'S': python += `qc.s(${gate.qubit})\n`; break;
        case 'T': python += `qc.t(${gate.qubit})\n`; break;
        case 'RX': python += `qc.rx(${gate.angle || 'np.pi/2'}, ${gate.qubit})\n`; break;
        case 'RY': python += `qc.ry(${gate.angle || 'np.pi/2'}, ${gate.qubit})\n`; break;
        case 'RZ': python += `qc.rz(${gate.angle || 'np.pi/2'}, ${gate.qubit})\n`; break;
        case 'CNOT':
          if (gate.controlQubit !== undefined) {
            python += `qc.cx(${gate.controlQubit}, ${gate.qubit})\n`;
          }
          break;
        case 'M': python += `qc.measure(${gate.qubit}, ${gate.qubit})\n`; break;
      }
    });
    
    python += `\n# Execute the circuit\n`;
    python += `backend = Aer.get_backend('qasm_simulator')\n`;
    python += `job = execute(qc, backend, shots=1024)\n`;
    python += `result = job.result()\n`;
    python += `counts = result.get_counts(qc)\n`;
    python += `print(counts)\n`;
    
    return python;
  };

  const formats = {
    qasm: { name: 'OpenQASM', content: generateQASM(), extension: '.qasm' },
    json: { name: 'JSON', content: generateJSON(), extension: '.json' },
    python: { name: 'Python (Qiskit)', content: generatePython(), extension: '.py' }
  };

  const handleCopy = async (format: string, content: string) => {
    try {
      await navigator.clipboard.writeText(content);
      setCopiedFormat(format);
      setTimeout(() => setCopiedFormat(null), 2000);
      toast({
        title: "Copied to clipboard",
        description: `${formats[format as keyof typeof formats].name} code copied successfully`
      });
    } catch (error) {
      toast({
        title: "Copy failed",
        description: "Failed to copy to clipboard",
        variant: "destructive"
      });
    }
  };

  const handleDownload = (format: string, content: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${circuit.name}${formats[format as keyof typeof formats].extension}`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast({
      title: "Download started",
      description: `${formats[format as keyof typeof formats].name} file downloaded`
    });
  };

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-4xl h-[80vh] quantum-panel neon-border">
        <DialogHeader>
          <DialogTitle className="text-quantum-glow flex items-center gap-2">
            Export Circuit: {circuit.name}
            <Badge variant="outline" className="text-xs">
              {circuit.gates.length} gates
            </Badge>
          </DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="qasm" className="flex-1 flex flex-col">
          <TabsList className="grid w-full grid-cols-3 bg-quantum-matrix">
            <TabsTrigger value="qasm">OpenQASM</TabsTrigger>
            <TabsTrigger value="json">JSON</TabsTrigger>
            <TabsTrigger value="python">Python</TabsTrigger>
          </TabsList>

          {Object.entries(formats).map(([key, format]) => (
            <TabsContent key={key} value={key} className="flex-1">
              <Card className="h-full quantum-panel">
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-quantum-glow">{format.name}</CardTitle>
                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleCopy(key, format.content)}
                        className="neon-border"
                      >
                        {copiedFormat === key ? (
                          <Check className="w-4 h-4 mr-1" />
                        ) : (
                          <Copy className="w-4 h-4 mr-1" />
                        )}
                        Copy
                      </Button>
                      <Button
                        onClick={() => handleDownload(key, format.content)}
                        size="sm"
                        className="bg-quantum-plasma hover:bg-quantum-plasma/80 text-quantum-void"
                      >
                        <Download className="w-4 h-4 mr-1" />
                        Download
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="bg-quantum-void rounded p-4 h-96 overflow-auto">
                    <pre className="text-sm font-mono text-quantum-neon whitespace-pre-wrap">
                      {format.content}
                    </pre>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          ))}
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}
