import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { useToast } from '@/components/ui/use-toast';
import { CircuitExporter } from '@/components/sdk/CircuitExporter';
import { QuantumBackendResult } from '@/services/quantumBackendService';
import { Gate } from '@/hooks/useCircuitState';
import { SimulationStep } from '@/hooks/usePostSimulationWorkflow';
import { Download, FileText, Image, Code, Database } from 'lucide-react';

interface EnhancedExportOptionsProps {
  result: QuantumBackendResult;
  gates: Gate[];
  numQubits: number;
  circuitName: string;
  simulationSteps: SimulationStep[];
}

export function EnhancedExportOptions({
  result,
  gates,
  numQubits,
  circuitName,
  simulationSteps
}: EnhancedExportOptionsProps) {
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  const exportToCSV = async () => {
    setIsExporting(true);
    try {
      const csvData = Object.entries(result.measurementProbabilities)
        .map(([state, prob]) => `${state},${prob},${result.counts?.[state] || 0}`)
        .join('\n');
      
      const csvContent = `State,Probability,Count\n${csvData}`;
      const blob = new Blob([csvContent], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      
      const a = document.createElement('a');
      a.href = url;
      a.download = `${circuitName}_results.csv`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast({
        title: "CSV Export Complete",
        description: "Measurement results exported successfully"
      });
    } catch (error) {
      toast({
        title: "Export Failed",
        description: "Failed to export CSV file",
        variant: "destructive"
      });
    }
    setIsExporting(false);
  };

  const exportToJSON = async () => {
    setIsExporting(true);
    try {
      const jsonData = {
        circuit: {
          name: circuitName,
          qubits: numQubits,
          gates: gates,
          depth: gates.length
        },
        simulation: {
          backend: result.backend,
          executionTime: result.executionTime,
          shots: Object.values(result.counts || {}).reduce((sum, count) => sum + count, 0)
        },
        results: {
          stateVector: result.stateVector,
          measurementProbabilities: result.measurementProbabilities,
          counts: result.counts,
          qubitStates: result.qubitStates,
          entanglement: result.entanglement
        },
        steps: simulationSteps.length > 0 ? simulationSteps : undefined
      };
      
      const jsonContent = JSON.stringify(jsonData, null, 2);
      const blob = new Blob([jsonContent], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      
      const a = document.createElement('a');
      a.href = url;
      a.download = `${circuitName}_complete_results.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast({
        title: "JSON Export Complete",
        description: "Complete simulation data exported"
      });
    } catch (error) {
      toast({
        title: "Export Failed",
        description: "Failed to export JSON file",
        variant: "destructive"
      });
    }
    setIsExporting(false);
  };

  const generateReproduciblePython = () => {
    const pythonCode = `# Quantum Circuit Simulation Results
# Generated by QOSim - ${new Date().toISOString()}
# Circuit: ${circuitName}

import numpy as np
import matplotlib.pyplot as plt
from qiskit import QuantumCircuit, execute, Aer
from qiskit.visualization import plot_histogram

# Original simulation results
execution_time = ${result.executionTime}  # ms
backend_used = "${result.backend}"
shots_used = ${Object.values(result.counts || {}).reduce((sum, count) => sum + count, 0)}

# Measurement counts from original simulation
original_counts = ${JSON.stringify(result.counts || {}, null, 2)}

# Create the circuit (use the Circuit Export tab for full circuit code)
qc = QuantumCircuit(${numQubits}, ${numQubits})

${gates.map(gate => {
  switch (gate.type) {
    case 'H': return `qc.h(${gate.qubit})`;
    case 'X': return `qc.x(${gate.qubit})`;
    case 'Y': return `qc.y(${gate.qubit})`;
    case 'Z': return `qc.z(${gate.qubit})`;
    case 'S': return `qc.s(${gate.qubit})`;
    case 'T': return `qc.t(${gate.qubit})`;
    case 'CNOT': return `qc.cx(${gate.qubits?.[0] || 0}, ${gate.qubits?.[1] || 1})`;
    case 'RX': return `qc.rx(${gate.angle || 0}, ${gate.qubit})`;
    case 'RY': return `qc.ry(${gate.angle || 0}, ${gate.qubit})`;
    case 'RZ': return `qc.rz(${gate.angle || 0}, ${gate.qubit})`;
    default: return `# ${gate.type} gate not implemented`;
  }
}).join('\n')}

# Add measurements
qc.measure_all()

# Execute the circuit
backend = Aer.get_backend('qasm_simulator')
job = execute(qc, backend, shots=shots_used)
result = job.result()
new_counts = result.get_counts(qc)

# Compare results
print("Original QOSim Results:")
for state, count in original_counts.items():
    prob = count / shots_used
    print(f"|{state}⟩: {count} ({prob:.4f})")

print("\\nNew Simulation Results:")
for state, count in new_counts.items():
    prob = count / shots_used
    print(f"|{state}⟩: {count} ({prob:.4f})")

# Visualize results
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
plot_histogram(original_counts, ax=ax1, title='QOSim Results')
plot_histogram(new_counts, ax=ax2, title='Reproduced Results')
plt.tight_layout()
plt.show()

# Print circuit
print("\\nCircuit Diagram:")
print(qc.draw())
`;
    
    const blob = new Blob([pythonCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${circuitName}_reproduce.py`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Python Code Generated",
      description: "Reproducible Python script downloaded"
    });
  };

  return (
    <div className="space-y-6">
      {/* Quick Export Actions */}
      <Card className="quantum-panel neon-border">
        <CardHeader>
          <CardTitle className="text-quantum-glow">Quick Export Actions</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <Button
              onClick={exportToCSV}
              disabled={isExporting}
              variant="outline"
              className="quantum-panel neon-border"
            >
              <Database className="w-4 h-4 mr-2" />
              CSV Results
            </Button>
            
            <Button
              onClick={exportToJSON}
              disabled={isExporting}
              variant="outline"
              className="quantum-panel neon-border"
            >
              <FileText className="w-4 h-4 mr-2" />
              JSON Data
            </Button>
            
            <Button
              onClick={generateReproduciblePython}
              disabled={isExporting}
              variant="outline"
              className="quantum-panel neon-border"
            >
              <Code className="w-4 h-4 mr-2" />
              Python Script
            </Button>
            
            <Button
              disabled={true}
              variant="outline"
              className="quantum-panel neon-border opacity-50"
            >
              <Image className="w-4 h-4 mr-2" />
              PDF Report
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Existing Circuit Exporter */}
      <div>
        <h3 className="text-lg font-semibold text-quantum-neon mb-4">Circuit Code Export</h3>
        <CircuitExporter
          gates={gates}
          simulationResult={result}
          numQubits={numQubits}
          circuitName={circuitName}
        />
      </div>

      {/* Export Status */}
      {simulationSteps.length > 0 && (
        <Alert>
          <Download className="h-4 w-4" />
          <AlertDescription>
            Step-by-step evolution data is included in JSON exports. 
            This contains the quantum state at each gate application for detailed analysis.
          </AlertDescription>
        </Alert>
      )}
    </div>
  );
}
