import React, { useEffect, useRef, useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Copy, Download, CheckCircle } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { EnhancedCircuitRenderer } from './EnhancedCircuitRenderer';

interface CircuitGate {
  id: string;
  type: string;
  qubit?: number;
  qubits?: number[];
  position: number;
  angle?: number;
}

interface CircuitChatResponseProps {
  gates: CircuitGate[];
  explanation: string;
  numQubits: number;
  circuitName?: string;
}

// Helper function to generate PennyLane code
const generatePennyLaneCode = (gates: CircuitGate[], numQubits: number, circuitName: string = 'quantum_circuit') => {
  let code = `# ${circuitName} - Generated by QOSim\n`;
  code += `import pennylane as qml\n`;
  code += `import numpy as np\n\n`;
  code += `# Define the device\n`;
  code += `dev = qml.device('default.qubit', wires=${numQubits})\n\n`;
  code += `@qml.qnode(dev)\n`;
  code += `def ${circuitName.replace(/\s+/g, '_').toLowerCase()}():\n`;
  
  const sortedGates = [...gates].sort((a, b) => a.position - b.position);
  
  sortedGates.forEach(gate => {
    switch (gate.type) {
      case 'H':
        code += `    qml.Hadamard(wires=${gate.qubit || 0})\n`;
        break;
      case 'X':
        code += `    qml.PauliX(wires=${gate.qubit || 0})\n`;
        break;
      case 'Y':
        code += `    qml.PauliY(wires=${gate.qubit || 0})\n`;
        break;
      case 'Z':
        code += `    qml.PauliZ(wires=${gate.qubit || 0})\n`;
        break;
      case 'S':
        code += `    qml.S(wires=${gate.qubit || 0})\n`;
        break;
      case 'T':
        code += `    qml.T(wires=${gate.qubit || 0})\n`;
        break;
      case 'CNOT':
        const cnotQubits = gate.qubits || [0, 1];
        code += `    qml.CNOT(wires=[${cnotQubits[0]}, ${cnotQubits[1]}])\n`;
        break;
      case 'CZ':
        const czQubits = gate.qubits || [0, 1];
        code += `    qml.CZ(wires=[${czQubits[0]}, ${czQubits[1]}])\n`;
        break;
      case 'SWAP':
        const swapQubits = gate.qubits || [0, 1];
        code += `    qml.SWAP(wires=[${swapQubits[0]}, ${swapQubits[1]}])\n`;
        break;
      case 'RX':
        const rxAngle = gate.angle || Math.PI / 2;
        code += `    qml.RX(${rxAngle}, wires=${gate.qubit || 0})\n`;
        break;
      case 'RY':
        const ryAngle = gate.angle || Math.PI / 2;
        code += `    qml.RY(${ryAngle}, wires=${gate.qubit || 0})\n`;
        break;
      case 'RZ':
        const rzAngle = gate.angle || Math.PI / 2;
        code += `    qml.RZ(${rzAngle}, wires=${gate.qubit || 0})\n`;
        break;
      case 'CCX':
      case 'TOFFOLI':
        const ccxQubits = gate.qubits || [0, 1, 2];
        if (ccxQubits.length >= 3) {
          code += `    qml.Toffoli(wires=[${ccxQubits[0]}, ${ccxQubits[1]}, ${ccxQubits[2]}])\n`;
        }
        break;
      default:
        code += `    # Unsupported gate: ${gate.type}\n`;
    }
  });
  
  code += `    return qml.probs(wires=range(${numQubits}))\n\n`;
  code += `# Execute the circuit\n`;
  code += `result = ${circuitName.replace(/\s+/g, '_').toLowerCase()}()\n`;
  code += `print("Probability distribution:", result)\n`;
  
  return code;
};

// Helper function to generate Qiskit code
const generateQiskitCode = (gates: CircuitGate[], numQubits: number, circuitName: string = 'quantum_circuit') => {
  let code = `# ${circuitName} - Generated by QOSim\n`;
  code += `from qiskit import QuantumCircuit, execute, Aer\n`;
  code += `from qiskit.visualization import plot_histogram\n`;
  code += `import numpy as np\n\n`;
  code += `# Create quantum circuit\n`;
  code += `qc = QuantumCircuit(${numQubits}, ${numQubits})\n\n`;
  
  const sortedGates = [...gates].sort((a, b) => a.position - b.position);
  
  sortedGates.forEach(gate => {
    switch (gate.type) {
      case 'H':
        code += `qc.h(${gate.qubit || 0})  # Hadamard gate\n`;
        break;
      case 'X':
        code += `qc.x(${gate.qubit || 0})  # Pauli-X gate\n`;
        break;
      case 'Y':
        code += `qc.y(${gate.qubit || 0})  # Pauli-Y gate\n`;
        break;
      case 'Z':
        code += `qc.z(${gate.qubit || 0})  # Pauli-Z gate\n`;
        break;
      case 'S':
        code += `qc.s(${gate.qubit || 0})  # S gate\n`;
        break;
      case 'T':
        code += `qc.t(${gate.qubit || 0})  # T gate\n`;
        break;
      case 'CNOT':
        const cnotQubits = gate.qubits || [0, 1];
        code += `qc.cx(${cnotQubits[0]}, ${cnotQubits[1]})  # CNOT gate\n`;
        break;
      case 'CZ':
        const czQubits = gate.qubits || [0, 1];
        code += `qc.cz(${czQubits[0]}, ${czQubits[1]})  # CZ gate\n`;
        break;
      case 'SWAP':
        const swapQubits = gate.qubits || [0, 1];
        code += `qc.swap(${swapQubits[0]}, ${swapQubits[1]})  # SWAP gate\n`;
        break;
      case 'RX':
        const rxAngle = gate.angle || Math.PI / 2;
        code += `qc.rx(${rxAngle}, ${gate.qubit || 0})  # RX rotation\n`;
        break;
      case 'RY':
        const ryAngle = gate.angle || Math.PI / 2;
        code += `qc.ry(${ryAngle}, ${gate.qubit || 0})  # RY rotation\n`;
        break;
      case 'RZ':
        const rzAngle = gate.angle || Math.PI / 2;
        code += `qc.rz(${rzAngle}, ${gate.qubit || 0})  # RZ rotation\n`;
        break;
      case 'CCX':
      case 'TOFFOLI':
        const ccxQubits = gate.qubits || [0, 1, 2];
        if (ccxQubits.length >= 3) {
          code += `qc.ccx(${ccxQubits[0]}, ${ccxQubits[1]}, ${ccxQubits[2]})  # Toffoli gate\n`;
        }
        break;
      default:
        code += `# Unsupported gate: ${gate.type}\n`;
    }
  });
  
  code += `\n# Add measurements\n`;
  code += `qc.measure_all()\n\n`;
  code += `# Execute the circuit\n`;
  code += `backend = Aer.get_backend('qasm_simulator')\n`;
  code += `job = execute(qc, backend, shots=1024)\n`;
  code += `result = job.result()\n`;
  code += `counts = result.get_counts(qc)\n`;
  code += `print("Measurement results:", counts)\n`;
  
  return code;
};

// Helper function to generate Cirq code
const generateCirqCode = (gates: CircuitGate[], numQubits: number, circuitName: string = 'quantum_circuit') => {
  let code = `# ${circuitName} - Generated by QOSim\n`;
  code += `import cirq\n`;
  code += `import numpy as np\n\n`;
  code += `# Create qubits\n`;
  code += `qubits = [cirq.GridQubit(0, i) for i in range(${numQubits})]\n\n`;
  code += `# Create circuit\n`;
  code += `circuit = cirq.Circuit()\n\n`;

  const sortedGates = [...gates].sort((a, b) => a.position - b.position);
  
  sortedGates.forEach(gate => {
    switch (gate.type) {
      case 'H':
        code += `circuit.append(cirq.H(qubits[${gate.qubit || 0}]))\n`;
        break;
      case 'X':
        code += `circuit.append(cirq.X(qubits[${gate.qubit || 0}]))\n`;
        break;
      case 'Y':
        code += `circuit.append(cirq.Y(qubits[${gate.qubit || 0}]))\n`;
        break;
      case 'Z':
        code += `circuit.append(cirq.Z(qubits[${gate.qubit || 0}]))\n`;
        break;
      case 'S':
        code += `circuit.append(cirq.S(qubits[${gate.qubit || 0}]))\n`;
        break;
      case 'T':
        code += `circuit.append(cirq.T(qubits[${gate.qubit || 0}]))\n`;
        break;
      case 'CNOT':
        const cnotQubits = gate.qubits || [0, 1];
        code += `circuit.append(cirq.CNOT(qubits[${cnotQubits[0]}], qubits[${cnotQubits[1]}]))\n`;
        break;
      case 'CZ':
        const czQubits = gate.qubits || [0, 1];
        code += `circuit.append(cirq.CZ(qubits[${czQubits[0]}], qubits[${czQubits[1]}]))\n`;
        break;
      case 'SWAP':
        const swapQubits = gate.qubits || [0, 1];
        code += `circuit.append(cirq.SWAP(qubits[${swapQubits[0]}], qubits[${swapQubits[1]}]))\n`;
        break;
      case 'RX':
        const rxAngle = gate.angle || Math.PI / 2;
        code += `circuit.append(cirq.rx(${rxAngle})(qubits[${gate.qubit || 0}]))\n`;
        break;
      case 'RY':
        const ryAngle = gate.angle || Math.PI / 2;
        code += `circuit.append(cirq.ry(${ryAngle})(qubits[${gate.qubit || 0}]))\n`;
        break;
      case 'RZ':
        const rzAngle = gate.angle || Math.PI / 2;
        code += `circuit.append(cirq.rz(${rzAngle})(qubits[${gate.qubit || 0}]))\n`;
        break;
      case 'CCX':
      case 'TOFFOLI':
        const ccxQubits = gate.qubits || [0, 1, 2];
        if (ccxQubits.length >= 3) {
          code += `circuit.append(cirq.CCX(qubits[${ccxQubits[0]}], qubits[${ccxQubits[1]}], qubits[${ccxQubits[2]}]))\n`;
        }
        break;
      default:
        code += `# Unsupported gate: ${gate.type}\n`;
    }
  });

  code += `\n# Add measurements\n`;
  code += `circuit.append(cirq.measure(*qubits, key='result'))\n\n`;
  code += `# Simulate the circuit\n`;
  code += `simulator = cirq.Simulator()\n`;
  code += `result = simulator.run(circuit, repetitions=1024)\n`;
  code += `print("Measurement results:", result.histogram(key='result'))\n`;

  return code;
};

export function CircuitChatResponse({ gates, explanation, numQubits, circuitName = "Generated Circuit" }: CircuitChatResponseProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const { toast } = useToast();
  const [copiedFramework, setCopiedFramework] = useState<string | null>(null);

  // Initialize the circuit visualizer
  useEffect(() => {
    if (canvasRef.current && gates.length > 0) {
      const canvas = canvasRef.current;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      // Set canvas size
      canvas.width = 600;
      canvas.height = Math.max(200, numQubits * 60 + 100);
      
      // Clear canvas
      ctx.fillStyle = 'hsl(var(--background))';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      
      // Circuit drawing parameters
      const startX = 80;
      const startY = 50;
      const wireSpacing = 50;
      const gateSpacing = 80;
      const gateSize = 30;
      
      // Draw qubit wires
      ctx.strokeStyle = 'hsl(var(--foreground))';
      ctx.lineWidth = 2;
      
      for (let i = 0; i < numQubits; i++) {
        const y = startY + i * wireSpacing;
        ctx.beginPath();
        ctx.moveTo(startX, y);
        ctx.lineTo(canvas.width - 50, y);
        ctx.stroke();
        
        // Draw qubit labels
        ctx.fillStyle = 'hsl(var(--foreground))';
        ctx.font = '14px monospace';
        ctx.textAlign = 'right';
        ctx.fillText(`q${i}`, startX - 10, y + 5);
      }
      
      // Group gates by position
      const positions = new Map<number, CircuitGate[]>();
      gates.forEach(gate => {
        const pos = gate.position || 0;
        if (!positions.has(pos)) {
          positions.set(pos, []);
        }
        positions.get(pos)!.push(gate);
      });
      
      // Draw gates
      ctx.font = '12px monospace';
      ctx.textAlign = 'center';
      
      Array.from(positions.keys()).sort((a, b) => a - b).forEach((position, index) => {
        const gatesAtPosition = positions.get(position)!;
        const x = startX + (index + 1) * gateSpacing;
        
        gatesAtPosition.forEach(gate => {
          if (gate.type === 'CNOT' && gate.qubits && gate.qubits.length >= 2) {
            // Draw CNOT gate
            const controlY = startY + (gate.qubits[0] || 0) * wireSpacing;
            const targetY = startY + (gate.qubits[1] || 1) * wireSpacing;
            
            // Control dot
            ctx.fillStyle = 'hsl(var(--primary))';
            ctx.beginPath();
            ctx.arc(x, controlY, 5, 0, 2 * Math.PI);
            ctx.fill();
            
            // Connection line
            ctx.strokeStyle = 'hsl(var(--primary))';
            ctx.lineWidth = 2;
            ctx.beginPath();
            ctx.moveTo(x, controlY);
            ctx.lineTo(x, targetY);
            ctx.stroke();
            
            // Target circle
            ctx.strokeStyle = 'hsl(var(--primary))';
            ctx.lineWidth = 3;
            ctx.beginPath();
            ctx.arc(x, targetY, 15, 0, 2 * Math.PI);
            ctx.stroke();
            
            // Target plus
            ctx.beginPath();
            ctx.moveTo(x - 10, targetY);
            ctx.lineTo(x + 10, targetY);
            ctx.moveTo(x, targetY - 10);
            ctx.lineTo(x, targetY + 10);
            ctx.stroke();
            
          } else {
            // Single qubit gate
            const qubit = gate.qubit || 0;
            const y = startY + qubit * wireSpacing;
            
            // Gate box
            ctx.fillStyle = 'hsl(var(--primary))';
            ctx.fillRect(x - gateSize/2, y - gateSize/2, gateSize, gateSize);
            
            // Gate border
            ctx.strokeStyle = 'hsl(var(--primary-foreground))';
            ctx.lineWidth = 1;
            ctx.strokeRect(x - gateSize/2, y - gateSize/2, gateSize, gateSize);
            
            // Gate label
            ctx.fillStyle = 'hsl(var(--primary-foreground))';
            ctx.fillText(gate.type, x, y + 4);
          }
        });
      });
    }
  }, [gates, numQubits]);

  const copyToClipboard = async (text: string, framework: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedFramework(framework);
      toast({
        title: "Copied to clipboard!",
        description: `${framework} code has been copied to your clipboard.`
      });
      
      // Clear the "copied" state after 2 seconds
      setTimeout(() => setCopiedFramework(null), 2000);
    } catch (error) {
      toast({
        title: "Failed to copy",
        description: "Could not copy code to clipboard.",
        variant: "destructive"
      });
    }
  };

  const handleExport = (framework: 'qiskit' | 'cirq' | 'pennylane') => {
    let code = '';
    
    switch (framework) {
      case 'qiskit':
        code = generateQiskitCode(gates, numQubits, circuitName);
        break;
      case 'cirq':
        code = generateCirqCode(gates, numQubits, circuitName);
        break;
      case 'pennylane':
        code = generatePennyLaneCode(gates, numQubits, circuitName);
        break;
    }
    
    copyToClipboard(code, framework.charAt(0).toUpperCase() + framework.slice(1));
  };

  return (
    <Card className="w-full space-y-4">
      <CardContent className="pt-6">
        {/* Circuit Name and Stats */}
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold">{circuitName}</h3>
          <div className="flex gap-2">
            <Badge variant="outline">{gates.length} gates</Badge>
            <Badge variant="outline">{numQubits} qubits</Badge>
            <Badge variant="outline">Depth: {Math.max(...gates.map(g => g.position), 0) + 1}</Badge>
          </div>
        </div>

        {/* Circuit Visualization */}
        <div className="mb-6">
          <div className="bg-card border rounded-lg p-4">
            <EnhancedCircuitRenderer
              gates={gates}
              numQubits={numQubits}
              width={600}
              height={Math.max(200, numQubits * 60 + 100)}
              showTooltips={true}
            />
          </div>
        </div>

        <Separator className="my-4" />

        {/* Step-by-step Explanation */}
        <div className="mb-6">
          <h4 className="text-sm font-medium mb-3">Circuit Explanation</h4>
          <div className="prose prose-sm max-w-none text-muted-foreground whitespace-pre-wrap">
            {explanation}
          </div>
        </div>

        <Separator className="my-4" />

        {/* Export Options */}
        <div>
          <h4 className="text-sm font-medium mb-3">Export Circuit Code</h4>
          <div className="flex flex-wrap gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => handleExport('qiskit')}
              className="flex items-center gap-2"
            >
              {copiedFramework === 'Qiskit' ? (
                <CheckCircle className="w-4 h-4 text-green-500" />
              ) : (
                <Copy className="w-4 h-4" />
              )}
              Export as Qiskit
            </Button>
            
            <Button
              variant="outline"
              size="sm"
              onClick={() => handleExport('cirq')}
              className="flex items-center gap-2"
            >
              {copiedFramework === 'Cirq' ? (
                <CheckCircle className="w-4 h-4 text-green-500" />
              ) : (
                <Copy className="w-4 h-4" />
              )}
              Export as Cirq
            </Button>
            
            <Button
              variant="outline"
              size="sm"
              onClick={() => handleExport('pennylane')}
              className="flex items-center gap-2"
            >
              {copiedFramework === 'Pennylane' ? (
                <CheckCircle className="w-4 h-4 text-green-500" />
              ) : (
                <Copy className="w-4 h-4" />
              )}
              Export as PennyLane
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}