// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gefzbonshhfqkiqfjull.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlZnpib25zaGhmcWtpcWZqdWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTYwNTMsImV4cCI6MjA2NzAzMjA1M30.8-OQeh3ZQQ41a_Mw0bFXjjdvC0mQfRD35zDKCONbzzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});