import React, { useState } from 'react';
import { Download, FileText, Code, FileCode } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { trackEvent } from '@/lib/analytics';

interface Gate {
  id: string;
  type: string;
  qubit?: number;
  qubits?: number[];
  position: number;
  angle?: number;
  label?: string;
  comment?: string;
}

interface ExportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  circuit: Gate[];
  circuitRef: React.RefObject<HTMLElement>;
  numQubits: number;
}

export function ExportDialog({ 
  open, 
  onOpenChange, 
  circuit, 
  circuitRef,
  numQubits 
}: ExportDialogProps) {
  const { toast } = useToast();

  const [options, setOptions] = useState({
    projectName: 'quantum_circuit'
  });

  const generateCircuitData = (gates: Gate[]) => {
    return gates
      .sort((a, b) => a.position - b.position)
      .map(gate => ({
        gate: gate.type,
        qubit: gate.qubit,
        qubits: gate.qubits,
        time: gate.position,
        angle: gate.angle
      }));
  };

  const handleExportJSON = () => {
    try {
      const data = generateCircuitData(circuit);
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${options.projectName}.json`;
      a.click();
      trackEvent('circuit_exported', { format: 'json', gateCount: circuit.length });
      toast({ title: "JSON exported successfully!" });
    } catch (error) {
      toast({ title: "Export failed", description: String(error), variant: "destructive" });
    }
  };

  const handleExportQASM = () => {
    try {
      let qasm = `OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q[${numQubits}];\ncreg c[${numQubits}];\n\n`;
      
      circuit.forEach(gate => {
        switch (gate.type) {
          case 'H':
            qasm += `h q[${gate.qubit}];\n`;
            break;
          case 'X':
            qasm += `x q[${gate.qubit}];\n`;
            break;
          case 'Z':
            qasm += `z q[${gate.qubit}];\n`;
            break;
          case 'CNOT':
            if (gate.qubits) qasm += `cx q[${gate.qubits[0]}],q[${gate.qubits[1]}];\n`;
            break;
          case 'RX':
            qasm += `rx(${gate.angle}) q[${gate.qubit}];\n`;
            break;
          case 'RY':
            qasm += `ry(${gate.angle}) q[${gate.qubit}];\n`;
            break;
          case 'M':
            qasm += `measure q[${gate.qubit}] -> c[${gate.qubit}];\n`;
            break;
        }
      });
      
      const blob = new Blob([qasm], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${options.projectName}.qasm`;
      a.click();
      trackEvent('circuit_exported', { format: 'qasm', gateCount: circuit.length });
      toast({ title: "QASM exported successfully!" });
    } catch (error) {
      toast({ title: "Export failed", description: String(error), variant: "destructive" });
    }
  };

  const handleExportPython = () => {
    try {
      let python = `# Quantum Circuit - ${options.projectName}\n`;
      python += `# Generated by QOSim\n\n`;
      python += `from qiskit import QuantumCircuit, execute, Aer\n`;
      python += `from qiskit.visualization import plot_histogram\n`;
      python += `import numpy as np\n\n`;
      python += `# Create quantum circuit\n`;
      python += `qc = QuantumCircuit(${numQubits}, ${numQubits})\n\n`;
      
      circuit.forEach(gate => {
        switch (gate.type) {
          case 'H':
            python += `qc.h(${gate.qubit})  # Hadamard gate\n`;
            break;
          case 'X':
            python += `qc.x(${gate.qubit})  # Pauli-X gate\n`;
            break;
          case 'Y':
            python += `qc.y(${gate.qubit})  # Pauli-Y gate\n`;
            break;
          case 'Z':
            python += `qc.z(${gate.qubit})  # Pauli-Z gate\n`;
            break;
          case 'CNOT':
            if (gate.qubits) python += `qc.cx(${gate.qubits[0]}, ${gate.qubits[1]})  # CNOT gate\n`;
            break;
          case 'RX':
            python += `qc.rx(${gate.angle || 'np.pi/2'}, ${gate.qubit})  # RX rotation\n`;
            break;
          case 'RY':
            python += `qc.ry(${gate.angle || 'np.pi/2'}, ${gate.qubit})  # RY rotation\n`;
            break;
          case 'RZ':
            python += `qc.rz(${gate.angle || 'np.pi/2'}, ${gate.qubit})  # RZ rotation\n`;
            break;
          case 'S':
            python += `qc.s(${gate.qubit})  # S gate\n`;
            break;
          case 'T':
            python += `qc.t(${gate.qubit})  # T gate\n`;
            break;
          case 'M':
            python += `qc.measure(${gate.qubit}, ${gate.qubit})  # Measurement\n`;
            break;
        }
      });
      
      python += `\n# Execute the circuit\n`;
      python += `backend = Aer.get_backend('qasm_simulator')\n`;
      python += `job = execute(qc, backend, shots=1024)\n`;
      python += `result = job.result()\n`;
      python += `counts = result.get_counts(qc)\n\n`;
      python += `# Display results\n`;
      python += `print("Measurement results:")\n`;
      python += `print(counts)\n\n`;
      python += `# Uncomment to visualize\n`;
      python += `# plot_histogram(counts)\n`;
      python += `# print(qc.draw())\n`;
      
      const blob = new Blob([python], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${options.projectName}.py`;
      a.click();
      trackEvent('circuit_exported', { format: 'python' as any, gateCount: circuit.length });
      toast({ title: "Python exported successfully!" });
    } catch (error) {
      toast({ title: "Export failed", description: String(error), variant: "destructive" });
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="quantum-panel border-quantum-glow/30 max-w-md">
        <DialogHeader>
          <DialogTitle className="text-quantum-glow flex items-center gap-2">
            <Download className="w-5 h-5" />
            Export Quantum Circuit
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {/* Export Options */}
          <Card className="quantum-panel border-quantum-glow/20">
            <CardContent className="p-4 space-y-4">
              <div className="space-y-2">
                <Label htmlFor="projectName">Project Name</Label>
                <Input
                  id="projectName"
                  value={options.projectName}
                  onChange={(e) => setOptions(prev => ({ ...prev, projectName: e.target.value }))}
                  placeholder="Enter project name"
                  className="neon-border"
                />
              </div>
            </CardContent>
          </Card>

          {/* Export Formats */}
          <Card className="quantum-panel border-quantum-glow/20">
            <CardContent className="p-4 space-y-3">
              <h3 className="font-semibold text-quantum-glow">Export Formats</h3>
              
              <div className="grid grid-cols-3 gap-2">
                <Button 
                  onClick={handleExportJSON} 
                  variant="outline" 
                  className="neon-border flex items-center gap-2"
                >
                  <FileText className="w-4 h-4" />
                  JSON
                </Button>

                <Button 
                  onClick={handleExportQASM} 
                  variant="outline" 
                  className="neon-border flex items-center gap-2"
                >
                  <Code className="w-4 h-4" />
                  QASM
                </Button>

                <Button 
                  onClick={handleExportPython} 
                  variant="outline" 
                  className="neon-border flex items-center gap-2"
                >
                  <FileCode className="w-4 h-4" />
                  Python
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </DialogContent>
    </Dialog>
  );
}