
import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { 
  Download, 
  Copy, 
  Code, 
  FileText, 
  Cpu, 
  Braces,
  Tag,
  Check
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface Gate {
  id: string;
  type: string;
  qubit?: number;
  qubits?: number[];
  position: number;
  angle?: number;
  label?: string;
  comment?: string;
}

interface ExportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  circuit: Gate[];
  numQubits: number;
  circuitName?: string;
}

export function QuantumCircuitExportDialog({ 
  open, 
  onOpenChange, 
  circuit, 
  numQubits,
  circuitName = 'quantum_circuit'
}: ExportDialogProps) {
  const [selectedFormat, setSelectedFormat] = useState('qasm');
  const [projectName, setProjectName] = useState(circuitName);
  const [version, setVersion] = useState('1.0.0');
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);
  const { toast } = useToast();

  const generateQASMCode = () => {
    let qasm = `OPENQASM 3.0;\ninclude "stdgates.inc";\n\n`;
    qasm += `// Circuit: ${projectName} v${version}\n`;
    qasm += `// Generated by QOSim Circuit Builder\n`;
    qasm += `// Date: ${new Date().toISOString()}\n\n`;
    qasm += `qubit[${numQubits}] q;\n`;
    qasm += `bit[${numQubits}] c;\n\n`;
    
    const sortedGates = [...circuit].sort((a, b) => a.position - b.position);
    
    sortedGates.forEach(gate => {
      const comment = gate.comment ? ` // ${gate.comment}` : '';
      switch (gate.type) {
        case 'H':
          qasm += `h q[${gate.qubit}];${comment}\n`;
          break;
        case 'X':
          qasm += `x q[${gate.qubit}];${comment}\n`;
          break;
        case 'Y':
          qasm += `y q[${gate.qubit}];${comment}\n`;
          break;
        case 'Z':
          qasm += `z q[${gate.qubit}];${comment}\n`;
          break;
        case 'S':
          qasm += `s q[${gate.qubit}];${comment}\n`;
          break;
        case 'T':
          qasm += `t q[${gate.qubit}];${comment}\n`;
          break;
        case 'RX':
          qasm += `rx(${gate.angle || 'pi/2'}) q[${gate.qubit}];${comment}\n`;
          break;
        case 'RY':
          qasm += `ry(${gate.angle || 'pi/2'}) q[${gate.qubit}];${comment}\n`;
          break;
        case 'RZ':
          qasm += `rz(${gate.angle || 'pi/2'}) q[${gate.qubit}];${comment}\n`;
          break;
        case 'CNOT':
          if (gate.qubits && gate.qubits.length >= 2) {
            qasm += `cx q[${gate.qubits[0]}], q[${gate.qubits[1]}];${comment}\n`;
          }
          break;
        case 'CZ':
          if (gate.qubits && gate.qubits.length >= 2) {
            qasm += `cz q[${gate.qubits[0]}], q[${gate.qubits[1]}];${comment}\n`;
          }
          break;
        case 'M':
          qasm += `c[${gate.qubit}] = measure q[${gate.qubit}];${comment}\n`;
          break;
        default:
          console.warn(`Unsupported gate type for QASM: ${gate.type}`);
      }
    });
    
    return qasm;
  };

  const generatePythonCode = () => {
    let python = `# Quantum Circuit: ${projectName} v${version}\n`;
    python += `# Generated by QOSim Circuit Builder\n`;
    python += `# Date: ${new Date().toISOString()}\n\n`;
    python += `from qiskit import QuantumCircuit, execute, Aer\n`;
    python += `from qiskit.visualization import plot_histogram\n`;
    python += `import numpy as np\n\n`;
    python += `def create_quantum_circuit():\n`;
    python += `    """Create and return the quantum circuit"""\n`;
    python += `    qc = QuantumCircuit(${numQubits}, ${numQubits})\n\n`;
    
    const sortedGates = [...circuit].sort((a, b) => a.position - b.position);
    
    sortedGates.forEach(gate => {
      const comment = gate.comment ? `  # ${gate.comment}` : '';
      switch (gate.type) {
        case 'H':
          python += `    qc.h(${gate.qubit})${comment}\n`;
          break;
        case 'X':
          python += `    qc.x(${gate.qubit})${comment}\n`;
          break;
        case 'Y':
          python += `    qc.y(${gate.qubit})${comment}\n`;
          break;
        case 'Z':
          python += `    qc.z(${gate.qubit})${comment}\n`;
          break;
        case 'S':
          python += `    qc.s(${gate.qubit})${comment}\n`;
          break;
        case 'T':
          python += `    qc.t(${gate.qubit})${comment}\n`;
          break;
        case 'RX':
          python += `    qc.rx(${gate.angle || 'np.pi/2'}, ${gate.qubit})${comment}\n`;
          break;
        case 'RY':
          python += `    qc.ry(${gate.angle || 'np.pi/2'}, ${gate.qubit})${comment}\n`;
          break;
        case 'RZ':
          python += `    qc.rz(${gate.angle || 'np.pi/2'}, ${gate.qubit})${comment}\n`;
          break;
        case 'CNOT':
          if (gate.qubits && gate.qubits.length >= 2) {
            python += `    qc.cx(${gate.qubits[0]}, ${gate.qubits[1]})${comment}\n`;
          }
          break;
        case 'CZ':
          if (gate.qubits && gate.qubits.length >= 2) {
            python += `    qc.cz(${gate.qubits[0]}, ${gate.qubits[1]})${comment}\n`;
          }
          break;
        case 'M':
          python += `    qc.measure(${gate.qubit}, ${gate.qubit})${comment}\n`;
          break;
      }
    });
    
    python += `\n    return qc\n\n`;
    python += `def run_circuit():\n`;
    python += `    """Execute the quantum circuit"""\n`;
    python += `    qc = create_quantum_circuit()\n`;
    python += `    \n`;
    python += `    # Execute on simulator\n`;
    python += `    backend = Aer.get_backend('qasm_simulator')\n`;
    python += `    job = execute(qc, backend, shots=1024)\n`;
    python += `    result = job.result()\n`;
    python += `    counts = result.get_counts(qc)\n`;
    python += `    \n`;
    python += `    print("Measurement results:")\n`;
    python += `    print(counts)\n`;
    python += `    \n`;
    python += `    # Uncomment to visualize\n`;
    python += `    # plot_histogram(counts)\n`;
    python += `    # print(qc.draw())\n`;
    python += `    \n`;
    python += `    return counts\n\n`;
    python += `if __name__ == "__main__":\n`;
    python += `    run_circuit()\n`;
    
    return python;
  };

  const generateJavaScriptCode = () => {
    let javascript = `// Quantum Circuit: ${projectName} v${version}\n`;
    javascript += `// Generated by QOSim Circuit Builder\n`;
    javascript += `// Date: ${new Date().toISOString()}\n\n`;
    javascript += `import { QOSimSDK } from '@/sdk/qosim-sdk';\n\n`;
    javascript += `/**\n * Create and configure the quantum circuit\n */\n`;
    javascript += `export async function createQuantumCircuit() {\n`;
    javascript += `  const sdk = new QOSimSDK();\n`;
    javascript += `  await sdk.initialize();\n\n`;
    javascript += `  // Create quantum circuit\n`;
    javascript += `  let circuit = sdk.createCircuit('${projectName}', ${numQubits});\n\n`;
    
    const sortedGates = [...circuit].sort((a, b) => a.position - b.position);
    
    sortedGates.forEach(gate => {
      const comment = gate.comment ? ` // ${gate.comment}` : '';
      const gateConfig = {
        type: gate.type,
        qubit: gate.qubit,
        ...(gate.qubits && { qubits: gate.qubits }),
        ...(gate.angle && { angle: gate.angle }),
        ...(gate.label && { label: gate.label })
      };
      
      javascript += `  // Add ${gate.type} gate\n`;
      javascript += `  circuit = sdk.addGate(circuit, ${JSON.stringify(gateConfig)});${comment}\n`;
    });
    
    javascript += `\n  return { sdk, circuit };\n}\n\n`;
    javascript += `/**\n * Execute the quantum circuit\n */\n`;
    javascript += `export async function runQuantumCircuit() {\n`;
    javascript += `  try {\n`;
    javascript += `    const { sdk, circuit } = await createQuantumCircuit();\n`;
    javascript += `    \n`;
    javascript += `    // Simulate circuit\n`;
    javascript += `    const result = await sdk.simulate(circuit, { shots: 1024 });\n`;
    javascript += `    \n`;
    javascript += `    console.log('Simulation results:', result);\n`;
    javascript += `    return result;\n`;
    javascript += `  } catch (error) {\n`;
    javascript += `    console.error('Error running quantum circuit:', error);\n`;
    javascript += `    throw error;\n`;
    javascript += `  }\n}\n\n`;
    javascript += `// Execute if running directly\n`;
    javascript += `if (typeof window !== 'undefined') {\n`;
    javascript += `  runQuantumCircuit().then(result => {\n`;
    javascript += `    console.log('Quantum circuit execution completed:', result);\n`;
    javascript += `  }).catch(error => {\n`;
    javascript += `    console.error('Failed to execute quantum circuit:', error);\n`;
    javascript += `  });\n`;
    javascript += `}\n`;
    
    return javascript;
  };

  const generateJSONCode = () => {
    const circuitData = {
      metadata: {
        name: projectName,
        version: version,
        created: new Date().toISOString(),
        generator: 'QOSim Circuit Builder',
        qubits: numQubits,
        gates: circuit.length
      },
      circuit: {
        qubits: numQubits,
        gates: circuit.map(gate => ({
          id: gate.id,
          type: gate.type,
          qubit: gate.qubit,
          qubits: gate.qubits,
          position: gate.position,
          angle: gate.angle,
          label: gate.label,
          comment: gate.comment
        }))
      },
      qfs: {
        version: version,
        collaborative: true,
        tags: ['quantum', 'circuit', 'qosim'],
        permissions: {
          read: true,
          write: true,
          execute: true
        }
      }
    };
    
    return JSON.stringify(circuitData, null, 2);
  };

  const formats = {
    qasm: { 
      name: 'OpenQASM 3.0', 
      content: generateQASMCode(), 
      extension: '.qasm',
      icon: Cpu
    },
    python: { 
      name: 'Python (Qiskit)', 
      content: generatePythonCode(), 
      extension: '.py',
      icon: Code
    },
    javascript: { 
      name: 'JavaScript (QOSim SDK)', 
      content: generateJavaScriptCode(), 
      extension: '.js',
      icon: Braces
    },
    json: { 
      name: 'JSON Circuit Data', 
      content: generateJSONCode(), 
      extension: '.json',
      icon: FileText
    }
  };

  const handleCopy = async (format: string) => {
    const content = formats[format as keyof typeof formats].content;
    try {
      await navigator.clipboard.writeText(content);
      setCopiedFormat(format);
      setTimeout(() => setCopiedFormat(null), 2000);
      toast({
        title: "Copied to clipboard",
        description: `${formats[format as keyof typeof formats].name} code copied successfully`
      });
    } catch (error) {
      toast({
        title: "Copy failed",
        description: "Failed to copy to clipboard",
        variant: "destructive"
      });
    }
  };

  const handleDownload = (format: string) => {
    const formatData = formats[format as keyof typeof formats];
    const blob = new Blob([formatData.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName}_v${version}${formatData.extension}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Download started",
      description: `${formatData.name} file downloaded successfully`
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-5xl h-[90vh] quantum-panel neon-border">
        <DialogHeader>
          <DialogTitle className="text-quantum-glow flex items-center gap-2">
            <Download className="w-5 h-5" />
            Export Quantum Circuit
            <Badge variant="outline" className="text-quantum-neon">
              {circuit.length} gates
            </Badge>
          </DialogTitle>
        </DialogHeader>

        <div className="flex flex-col gap-4 h-full">
          {/* Configuration Section */}
          <Card className="quantum-panel neon-border">
            <CardHeader>
              <CardTitle className="text-sm text-quantum-glow flex items-center gap-2">
                <Tag className="w-4 h-4" />
                Export Configuration
              </CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="project-name" className="text-quantum-neon">Project Name</Label>
                <Input
                  id="project-name"
                  value={projectName}
                  onChange={(e) => setProjectName(e.target.value)}
                  className="quantum-panel neon-border"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="version" className="text-quantum-neon">Version (QFS)</Label>
                <Input
                  id="version"
                  value={version}
                  onChange={(e) => setVersion(e.target.value)}
                  className="quantum-panel neon-border"
                />
              </div>
            </CardContent>
          </Card>

          {/* Export Formats */}
          <div className="flex-1 min-h-0">
            <Tabs value={selectedFormat} onValueChange={setSelectedFormat} className="h-full flex flex-col">
              <TabsList className="grid w-full grid-cols-4 quantum-tabs">
                {Object.entries(formats).map(([key, format]) => {
                  const Icon = format.icon;
                  return (
                    <TabsTrigger key={key} value={key} className="quantum-tab">
                      <Icon className="w-4 h-4 mr-2" />
                      {format.name.split(' ')[0]}
                    </TabsTrigger>
                  );
                })}
              </TabsList>

              {Object.entries(formats).map(([key, format]) => (
                <TabsContent key={key} value={key} className="flex-1 min-h-0">
                  <Card className="h-full quantum-panel neon-border">
                    <CardHeader>
                      <div className="flex items-center justify-between">
                        <CardTitle className="text-quantum-glow">{format.name}</CardTitle>
                        <div className="flex gap-2">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => handleCopy(key)}
                            className="neon-border"
                          >
                            {copiedFormat === key ? (
                              <Check className="w-4 h-4 mr-2" />
                            ) : (
                              <Copy className="w-4 h-4 mr-2" />
                            )}
                            Copy
                          </Button>
                          <Button
                            onClick={() => handleDownload(key)}
                            size="sm"
                            className="bg-quantum-plasma hover:bg-quantum-plasma/80 text-quantum-void"
                          >
                            <Download className="w-4 h-4 mr-2" />
                            Download
                          </Button>
                        </div>
                      </div>
                    </CardHeader>
                    <CardContent className="h-full pb-4">
                      <Textarea
                        value={format.content}
                        readOnly
                        className="font-mono text-sm h-full resize-none quantum-panel neon-border"
                      />
                    </CardContent>
                  </Card>
                </TabsContent>
              ))}
            </Tabs>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
